### ISSUE TITLE
multiple elfeed buffer

### ISSUE THREAD

**Issue by seblemaguer** [skeeto/elfeed#102]
Hello,

I have a tiny question. Does elfeed support multiple buffer like  :
  - list of entries for url1 -> buffer 1 
  - list of entries for url2 -> buffer 2

Thanks

**Comment by skeeto** [comment]
My very early plans included multiple "search" buffers, just like
Notmuch. However, after using it privately on my own in early testing I
concluded it wasn't really necessary and scrapped the idea. I'm still
not convinced it's useful enough to warrant the additional complexity.

Right now it could be faked by messing with elfeed-search-buffer. The
filter in effect is already a buffer local value, so it would mostly
just work. A real solution requires elfeed-show and the live search
filtering to keep track of which search buffer spawned it. The hard part
is working out the UI for managing multiple search buffers.

The typical way people accomplish what I think you want is to make key
bindings for specific filters, which are essentially different "views"
of the listing. For example, you might bind a filter for url1 to the "1"
key and url2 to the "2" key, etc. Some people (including me) use a
rotation where pressing the same key rotates through a list of filters.

**Comment by seblemaguer** [comment]
Ah yes nice trick. Thanks for the tip
