### ISSUE TITLE
Split panes?

### ISSUE THREAD

**Issue by seanleblanc** [skeeto/elfeed#103]
Is it possible to have return key (instead of opening a new buffer that fills up entire pane) either split the pane and show content of link in another buffer (lower part of screen, preferably), or update the lower pane with new content if it's already been split?

**Comment by skeeto** [comment]
I don't think there's any easy way to do this right now, though there
probably should be. Perhaps a "elfeed-show-switch-function" variable
that controls the buffer is displayed. The difficultly is that each
entry gets its own buffer, and after all these years I still don't
understand how to control window placement programatically in Emacs.

In theory I do this:

   (defvar elfeed-show-switch-function #'switch-to-buffer)

(defun elfeed-show-find-window ()
  (cl-loop for window in (window-list)
           for buffer = (window-buffer window)
           for mode = (with-current-buffer buffer major-mode)
           when (eq mode 'elfeed-show-mode)
           return window))

**Comment by skeeto** [comment]
(GitHub swallowed all my e-mail formatting, so reposting it directly.)

I don't think there's any easy way to do this right now, though there probably should be. Perhaps a `elfeed-show-switch-function` variable that controls the buffer is displayed. The difficultly is that each entry gets its own buffer, and after all these years I still don't understand how to control window placement programatically in Emacs.

In theory I do this in `elfeed-show.el`:

~~~el
(defvar elfeed-show-switch-function #'switch-to-buffer)

(defun elfeed-show-find-window ()
  (cl-loop for window in (window-list)
           for buffer = (window-buffer window)
           for mode = (with-current-buffer buffer major-mode)
           when (eq mode 'elfeed-show-mode)
           return window))
~~~

Then the user can do this:

~~~el
(defun foo (buffer)
  (let ((target (elfeed-show-find-window)))
    (if target
        (setf (window-buffer target) buffer)
      (pop-to-buffer buffer))))

(setf elfeed-show-switch-function #'foo)
~~~

But this still randomly selects windows as far as I can tell. Someone who knows what they're doing will have to look at this.

**Comment by algernon** [comment]
For what its worth, this is what I did to make split pane work:

```elisp
(defun elfeed-show-entry (entry)
  "Display ENTRY in the current buffer."
  (let ((title (elfeed-entry-title entry)))
    (split-window-right-and-focus) ;; <-
    (switch-to-buffer (get-buffer-create (format "*elfeed %s*" title)))
    (unless (eq major-mode 'elfeed-show-mode)
      (elfeed-show-mode))
    (setq elfeed-show-entry entry)
    (elfeed-show-refresh)))

(defun elfeed-kill-buffer ()
  "Kill the current buffer."
  (interactive)
  (evil-window-left 1) ;; <-
  (kill-buffer (other-buffer)) ;; <- changed current-buffer to other-buffer
  (delete-other-windows)) ;; <-
```

Depends on `evil` for `evil-window-left`, but that's a hack I'd like to get rid of. My changes are marked with arrows in the comments.

I will look at other packages that do these kinds of stuff, and borrow ideas from there, and then submit a PR once I'm happy with the results.

**Comment by skeeto** [comment]
@algernon 
Thanks! That makes things easy for me.

**Comment by chongchonghe** [comment]
Thanks for this post. I found it useful. How to make the Enter key split the window vertically (which I found more useful) instead of horizontally?
