### ISSUE TITLE
[feature] Add garbage colection for pending updates

### ISSUE THREAD

**Issue by Fuco1** [skeeto/elfeed#107]
I just checked elfeed and it had over 5000 "feeds pending".  Now I'm running (elfeed-unjam) in a loop to get rid of that.

It would be nice to have some built-in garbage collection for these.

**Comment by skeeto** [comment]
`elfeed-unjam` exists to work around bugs in either url-queue (part of Emacs) or some subsystem below it. Requests to url-queue are supposed to timeout if they take more than `url-queue-timeout` seconds to complete. In theory this is the garbage collector you're asking for. Unfortunately it doesn't always work correctly, with requests occasionally remaining in permanent limbo, neither timing out nor completing. If too many requests get stuck in limbo, then no additional requests will be attempted. It only happens occasionally, so `elfeed-unjam` is there to reset url-queue.

`elfeed-unjam` *should* be clearing all requests from the queue in one call regardless of their status, so a loop shouldn't be needed. What do you mean you need to run it in a loop?

**Comment by Fuco1** [comment]
It only clears 5 at a time for me, I had to run it 1000 times to clean up everything.

**Comment by Fuco1** [comment]
Fixed by upgrading to the latest release.
