### ISSUE TITLE
tag-specific display face?

### ISSUE THREAD

**Issue by titaniumbones** [skeeto/elfeed#108]
I would like to be able to change the display face of a given post if it is tagged with "starred".  Would htis be hard to do/ How would you recommend doing it?

**Comment by titaniumbones** [comment]
(so, e.g., maybe I would change the color or the font weight...)

**Comment by skeeto** [comment]
I *was* going to answer that "unread" is a special tag and there's not
currently a way to extend this feature. But as I was typing I realized
how easy it would be to fix.

You can now do exactly what you want once you update to this latest
commit. Take a look at elfeed-search-face-alist.

**Comment by titaniumbones** [comment]
I don't think I ever responded to say "thanks!"  This is really helpful for me, much appreciated.

**Comment by skeeto** [comment]
Thank you for the idea. I've already been making use of it myself. Check
out the new screenshot in the README.
