### ISSUE TITLE
How to set a feed's encode?

### ISSUE THREAD

**Issue by tumashu** [skeeto/elfeed#129]
my a feed is encode with "gb2312", but other feeds are utf-8, how to deal with this "gb2312" feed? ?

**Comment by skeeto** [comment]
Can you share the URL for that feed?

The two different ways the encoding would be communicated is in the
Content-Type header (optional) from the server and the XML header
(required). I believe Elfeed handles it correctly so long as it's
communicated correctly. I just tested it now with a GB2312 encoded feed
and a Content-Type of application/xml and it worked as I expected, so
I'll need to see the troublesome feed.

**Comment by tumashu** [comment]
```
http://news.baidu.com/n?cmd=1&class=technnews&tn=rss
```

**Comment by skeeto** [comment]
Yup, that's some real mojibake there. My test case was too trivial. I'll
try to figure this one out (recode-region?).

**Comment by skeeto** [comment]
Can you verify that ad12a52 fixes this? It's been pushed to master so
it's already part of Elfeed. The previous decode-coding-region wasn't
working as needed so I switched it to recode-region. Plus there was a
bug related to the region changing with the encoding.

**Comment by tumashu** [comment]
works, thanks!
