### ISSUE TITLE
syncing database between computers - why not as simple as syncing .elfeed?

### ISSUE THREAD

**Issue by benmaughan** [skeeto/elfeed#131]
Thanks for elfeed, I've been using it for a few days and really like it so far!

I saw on the Readme that database syncing between computers is something you are thinking about adding. I was curious why it is not as simple as syncing the .elfeed directory? I've tried this and it doesn't seem to work but it was not obvious to me why not!

**Comment by skeeto** [comment]
The index file in the .elfeed/ directory contains a huge s-expression.
It's a data structure of all the feeds and entries, including several
indices for fast queries. Merging two .elfeed/ directories requires
merging these data structures. The actual merge wouldn't be very
complicated, but it's not very useful unless it can be automated, which
needs a useful interface, etc.

The files under the data/ directory can be merged directly without any
special handling. If two files have the same name, then they have the
same content.

More: http://nullprogram.com/blog/2013/09/09/

**Comment by benmaughan** [comment]
Thanks for the information. I've been experimenting and have found that if I make a copy of my .elfeed directory then tag some entries (say with "starred") and quit elfeed, then copy the backup .elfeed directory back again (that has no starred entries), the tags are still there next time I start elfeed. 

The same is not true if I quit emacs before copying the backup .elfeed directory back again. In this case I see no starred entries, which is as I would expect since the backup .elfeed had no starred entries.

I presume that this is because the database is being stored in memory and is getting written back to the disk even after I quit elfeed (and kill the elfeed buffer). If this is the case, is it possible to force emacs to flush the database from memory and reread the version on disk?

**Comment by skeeto** [comment]
Currently, the database is only saved when you exit Emacs or you kill
the Elfeed search buffer. Just quitting with "q" (burying the buffer)
doesn't save, which probably gave you the illusion that your first
backup worked fine. If you want to force the save manually, use
elfeed-db-save. You can force a reload from the filesystem with
elfeed-db-load.

**Comment by benmaughan** [comment]
That was useful thanks. I wrapped my functions to open and close elfeed with loads and saves of the index respectively. Now I can sync my .elfeed directory between my laptop and desktop and my tags and articles are all copied across correctly. Cheers!

**Comment by skeeto** [comment]
Cool, I'm glad you figured out a solution.
