### ISSUE TITLE
Suggest a feature: save full article to elfeed db

### ISSUE THREAD

**Issue by tumashu** [skeeto/elfeed#134]
When I type 'b' on a entry, elfeed will open full article with eww, is it possible add a command, which can
save content in eww buffer to elfeed db, or convert eww buffer content to org format then save to db?

**Comment by skeeto** [comment]
It already does this with the entry's feed content. If you hit enter in
the search buffer, the entry is displayed in a buffer similar to eww.
However, external elements, such as images, are not saved.

**Comment by tumashu** [comment]
I want to use full article with images to replace summay article:-)
