### ISSUE TITLE
Add a simple "Multi-Mark" feature:

### ISSUE THREAD

**Issue by tumashu** [skeeto/elfeed#135]
Multi mark is a very useful feature, but elfeed is not include, suggest add, the below is a simple way:
1. Add a buildin tag as Mark tag, for example:  "Select" or "Mark"
2. Add a function, which let elfeed commands can deal with entrys which have special tag.
3. Make sure the follow commands can deal with "Mark tag"
4. When commands finish, clean all Mark-tag 
```
    RET: view selected entry in a buffer
    b: open selected entries in your browser (browse-url)
    y: copy selected entries URL to the clipboard
    r: mark selected entries as read
    u: mark selected entries as unread
    +: add a specific tag to selected entries
    -: remove a specific tag from selected entries
```

**Comment by skeeto** [comment]
Elfeed's built-in actions already work on the active region, so the
conventional way to do this in Elfeed is to use a filter and a region.
Filter mostly to the entries you want to act upon, create a region that
touches the selected entries, which may be the entire buffer, then
perform the action (b, +, -, etc.).

Every morning I do my first update for the day as I start my breakfast,
filtering on unread entries (my default). Once it's done updating, I
mark the entire buffer ("C-x h") and then hit "b" to view everything in
my browser.

**Comment by tumashu** [comment]
This is a good tip, thanks!
