### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by caadar** [skeeto/elfeed#139]
![typo](https://cloud.githubusercontent.com/assets/15320726/11853418/e1a9c98a-a44e-11e5-971d-79cf723add28.png)

**Comment by skeeto** [comment]
This looks like an artifact of the customization system. It's printing
the description string from defgroup up against the group/package name.
As far as I know it's not supposed to contain leading spaces (unlike the
modeline lighter).

**Comment by caadar** [comment]
Well, I check it and see the same with e.g. Notmuch. It's Emacs 'feature'.
