### ISSUE TITLE
[Feature] Clean up db

### ISSUE THREAD

**Issue by ghost** [skeeto/elfeed#147]
Sometimes I have to clean the data to index content when the tags are changed or for test, use elfeed-org and sometimes to update the list in .org and run elfeed-org but not updated \* elfeed-search *, I have been clean elfeed-db.el variables and delete the directory for re-index, possibly a bug elfeed-org but would be good to have a cleaning function.

It would be great to have a function to clean the database and directory to re-index the content.

**Comment by skeeto** [comment]
I don't understand your problem and what you need. Since you mentioned
testing I'll tell you about my two approaches to testing Elfeed without
interfering with my personal database.

For unit tests there's a test harness, `with-elfeed-test`, in
test/elfeed-db.el. It runs the body in a temporary, throwaway database.

For larger system tests, I change my HOME directory.

    rm -rf testhome
    mkdir testhome
    make compile
    HOME=$PWD/testhome emacs -L . -l elfeed.elc -f elfeed

This runs Elfeed on an empty database with an empty Emacs configuration
so that I can test it out in a clean environment.

**Comment by Distopico** [comment]
Basically a command to force restart feeds, delete cache, if I delete the folder manually .feed where lives the information, back to emacs and pressed 'G' there have still feeds and need restart emacs for re-index

**Comment by ldionmarcil** [comment]
I'm getting this as well. Any way to clear the database at run-time? I deleted ~/.elfeed and re-ran `elfeed-search-fetch` but the old, removed tags are still applied to entries.

**Comment by skeeto** [comment]
You must completely exit Emacs when you delete the index file. Otherwise
Emacs will keep using the version loaded into memory, and it will
restore it when you exit Emacs.

**Comment by ldionmarcil** [comment]
Is there no way to clear the "version loaded into memory"? Reloading
emacs to clear tags on a rss entry sounds quite inconvenient.

**Comment by tmalsburg** [comment]
FWIW, I think a function for cleaning the DB would be very useful.  I'm new to elfeed and still playing with the configuration.  My feed is basically a record of all my failed attempts to configure elfeed.  Would love to be able to clean this up without messing without having to learn about elfeed's internals.

**Comment by dustinlacewell-wk** [comment]
Ran into this same thing.

**Comment by RosalesJ** [comment]
Adding my voice here, this feature would be nice.

**Comment by apnewberry** [comment]
@tmalsburg @dustinlacewell-wk @RosalesJ Looks like https://github.com/skeeto/elfeed/commit/5abb05392cdfaea1d1ec4c54138091d19c509d99 adds `(elfeed-db-unload)` which worked for me.

**Comment by daraul** [comment]
I am still a little confused as to how I go about clearing the database to "start over". Do I just do `elfeed-db-unload`, then delete the directory at `elfeed-db-directory`?

**Comment by rileyrg** [comment]
> I am still a little confused as to how I go about clearing the database to "start over". Do I just do `elfeed-db-unload`, then delete the directory at `elfeed-db-directory`?

I'm here with you. I cant get rid of my data after changing my feeds (also using elfeed-org btw).
