### ISSUE TITLE
Error while getting a feed

### ISSUE THREAD

**Issue by cordawyn** [skeeto/elfeed#148]
Hello!
I'm getting `Wrong type argument: number-or-marker-p, nil` error when trying to read "https://duck.co/blog/topic/Activity/rss". XML looks valid, so I guess there might be some problem with emacs libraries.

Emacs 24.4.1

**Comment by skeeto** [comment]
This Atom feed (despite "rss" in the URL) is invalid for a number of
reasons. Elfeed toleratores all of these problems *except* for the
missing "updated" element. None of the entries have dates and Atom
requires dates.

https://validator.w3.org/feed/check.cgi?url=https://duck.co/blog/topic/Activity/rss

RSS entries are permitted to lack dates, and even when dates are
provided, RSS under-specifies the format. Elfeed has heuristics to
determine reasonable dates for RSS entries no matter what garbage is
provided in the pubDate field, if any. However, Atom is far more strict
and has very precise date requirements, so Elfeed doesn't use any
heuristics, leading to this error when the date is missing.

At minimum Elfeed should have a more informative error message. I've
never seen this particular situation before, so it hasn't come up. I
*may* add the RSS date heuristics to the Atom parser, but at the same
time I like the idea strict Atom handling. Its specification is strict
and the vast majority of Atom feeds are well-conforming, unlike RSS
which is a huge mess.

**Comment by cordawyn** [comment]
I also appreciate strict handling, no problem. Thanks for looking it up for
me!
I think you can close this issue then.
