### ISSUE TITLE
support for figure tag?

### ISSUE THREAD

**Issue by xahlee** [skeeto/elfeed#149]
the html5 “figure” tag in the “content” tag with “type="xhtml"” isn't displaying.

Example:

    <content type="xhtml">
      <div xmlns="http://www.w3.org/1999/xhtml">
    
        <figure>
          <img src="cat.jpg" alt="" width="1024" height="768" />
          <figcaption>cat</figcaption>
        </figure>
    
      </div>
    </content>

I think that's valid. Last time i checked, there's no xhtml5 spec, but seems whatever new tag in html5 is carried over to xhtml syntax.

**Comment by skeeto** [comment]
I figured you'd have a good test for me on one of your own feeds, and I was right. You've always exercised Atom to its fullest!

http://ergoemacs.org/emacs/blog.xml

It looks like you noticed that I fixed this issue (directly embedded XHTML) last month. Does the latest unstable MELPA version work for you? That Paul Graham figure picture seems to work fine.

I should probably tag a new release so the people following stable get the fix.

**Comment by xahlee** [comment]
ah, it is showing up! I must have done something wrong before. Before, the figure tag flashed for a sec (or something flashed for a sec) then disappeared. Maybe it is still loading the pic or something... but anyway, bad bug report. Thank you!
