### ISSUE TITLE
Variable pitch mode

### ISSUE THREAD

**Issue by Andre0991** [skeeto/elfeed#150]
Hi

First, thanks for `elfeed`.

I'd like to know whether it's possible to use  `variable-pitch-mode` in the `*elfeed-search*` buffer.
Currently they don't play well because the alignment is based on columns, which only works on monospaced fonts.

Is there any work around?

Thanks
André

**Comment by a13ph** [comment]
there is at least this somewhat relevant code which makes proportional fonts align
https://github.com/esessoms/propindent-mode

**Comment by Andre0991** [comment]
I think this is what I want. Thanks @a13ph.
