### ISSUE TITLE
CDATA in entry title not rendered

### ISSUE THREAD

**Issue by aksarkar** [skeeto/elfeed#155]
Example feed: http://connect.biorxiv.org/biorxiv_xml.php?subject=genetics+genomics

The title appears neither in the search buffer nor in individual entries.

elfeed 20160127.1730 (installed via melpa)
GNU Emacs 24.5.1

**Comment by skeeto** [comment]
This is a bug in Elfeed's companion library xml-query. The problem isn't
that the CDATA isn't being read, but rather that the CDATA is causing
the XML parser to break the title up into multiple strings. Elfeed only
selects the first string (a newline in this case) under the title
element. It should instead be concatenating all the strings under the
title. The "*" component in the xml-query should do this automatically,
but currently it is not. I'll need to figure out how to fix this without
breaking something else.
