### ISSUE TITLE
font display problem (italic to normal)

### ISSUE THREAD

**Issue by llcc** [skeeto/elfeed#160]
Hi @skeeto 

The font display of the article have been changed to italic as the image shows. Can I make it to normal with some configs? 

![image](https://cloud.githubusercontent.com/assets/3996879/14934057/739c8f76-0edf-11e6-9a78-b70819909be6.png)

Best regards.
llcc

**Comment by skeeto** [comment]
I'm unable to reproduce it with the same article in either my own config
or the default Emacs config. For some reason shr (Emacs' built-in HTML
renderer) is choosing an italics face for the body text. My guess is
that it's some kind of interaction issue between shr and your theme.

What version of Emacs and what theme are you using? What does it say
when you put the point over the italicized text and M-x what-face?

**Comment by llcc** [comment]
@skeeto thanks! I solved the problem according to what you said! so i think i ought to close this issue.
