### ISSUE TITLE
Symbol’s function definition is void: elfeed-search-buffer

### ISSUE THREAD

**Issue by heikkil** [skeeto/elfeed#176]
I've been flummoxed by spurious failures to start elfeed. This can happen even after I have already used elfeed and left the search buffer open. The only way to regain the functionality have been to restart emacs, and even that does not work every time. Any ideas how to debug this?

I've bound M-x elfeed to a key combo and always start or resume using it by pressing the keys.

```
Debugger entered--Lisp error: (void-function elfeed-search-buffer)
  elfeed-search-buffer()
  #[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/lehvasho/src/emacs-literal-config/.cask/25.1.50.1/elpa/elfeed-20160911.1353/elfeed.elc" . 15465) nil]()
  ad-Advice-elfeed(#[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/lehvasho/src/emacs-literal-config/.cask/25.1.50.1/elpa/elfeed-20160911.1353/elfeed.elc" . 15465) nil])
  apply(ad-Advice-elfeed #[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/lehvasho/src/emacs-literal-config/.cask/25.1.50.1/elpa/elfeed-20160911.1353/elfeed.elc" . 15465) nil] nil)
  elfeed()
  funcall-interactively(elfeed)
  call-interactively(elfeed nil nil)
  command-execute(elfeed)
```

I am using elfeed-org.

I've tried eval'ing the whole elfeed-search.el buffer but that does not help. Then I tried eval'ing functions that are reported to be void, but there is always the next function down the line that is void. I gave that up eventually. Having to do this one by one can not be right!

Is the most probable culprit elfeed, the new version of emacs, or my emacs configuration?

I am running
GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G31)) of 2016-08-30

**Comment by skeeto** [comment]
How do you have Elfeed installed? Is it through Melpa? I see Cask in
your backtrace, suggesting it's pulled in via Cask (via Melpa). I wonder
if maybe it has to do with autoloading, though, to the contrary, you
said it breaks down after it's already loaded. This means somehow
functions are getting undefined (very unusual) sometime after being
loaded.

The second function in the backtrace is the compiled form of M-x elfeed.
So somehow that function is correctly being loaded (from elfeed.el), but
elfeed-search-buffer (from elfeed-search.el) is not. The (require
'elfeed-search) comes before the definition of M-x elfeed, so I can't
think of how this might be happening.

As far as I know, Elfeed works fine in the Emacs 25 pre-release builds,
so I don't think that's the culprit. I gave it another check just now to
be sure. Maybe it has something to do with the way Elfeed is being
compiled with your setup.

**Comment by heikkil** [comment]
Thanks for the effort of trying to look into this problem. I was not expecting much unless someone has same symptoms. Let's wait for that.

Further details:

- Everything is installed from Melpa via Cask and using use-package.
- elfeed is the only package affected (out of 185 in my Cask file)

**Comment by heikkil** [comment]
Recent changes (efe6723, 5028a4f) to fix the issue, Don't lazily load elfeed-show.el (#202) seem to have fixed this one, too!

Hurrah!
