### ISSUE TITLE
How to set face for read tag entries

### ISSUE THREAD

**Issue by stardiviner** [skeeto/elfeed#179]
I have a function to mark readed entry with tag `read`
And also set `elfeed-search-face-alist` for `read` tag like this:
```elisp
  (defun elfeed-mark-read ()
    (interactive)
    ;; (elfeed-search-untag-all-unread)
    (elfeed-search-untag-all 'unread)
    (previous-line)
    (elfeed-search-tag-all 'read)
    )
  (define-key elfeed-search-mode-map (kbd "r") 'elfeed-mark-read)
  
  ;; different face colors for different kinds of content (videos, podcast, comics)
  ;; Mapping of tags to faces in the Elfeed entry listing.
  (setq elfeed-search-face-alist
        '((unread (:foreground "light grey"))
          (read (:background (color-darken-name (face-background 'default) 3)
                             :foregroound "#444444"))
          (Emacs (:foreground "SteelBlue"))
          (Linux (:foreground "tomato"))
          (Arch (:foreground "cyan"))
          (Programming
           (:background (color-darken-name (face-background 'default) 3)
                        :foreground "YellowGreen"
                        ))))
```

But looks like those faces does not apply.

Can you show me how to custom them?

**Comment by skeeto** [comment]
Don't put properties directly in elfeed-search-face-alist. Define a face
with defface, then list its name in the alist with its tag. For example:

(defface foo-tag
  '((t :foreground "#49f"))
  "Marks foo tags.")

(push '(foo foo-tag)
      elfeed-search-face-alist)

**Comment by stardiviner** [comment]
Bt the way, how to auto add tag `read` after `[RET]` open an entry?

**Comment by skeeto** [comment]
Make your own function that wraps elfeed-search-show-entry (the default
binding for RET) and bind it instead, or advise it (i.e. defadvice). But
perhaps the tags it manipulates should be configurable through a
customization variable.

**Comment by stardiviner** [comment]
@skeeto Thanks for your advice. I construct a simple function to use variable as argument for mark tag around action.
