### ISSUE TITLE
Test elfeed-float-time fails

### ISSUE THREAD

**Issue by dogsleg** [skeeto/elfeed#180]
Hi,

I use Emacs 24.5.1 under Debian GNU/Linux testing+unstable, amd64. Running `make test' is not successful:

`$ make test
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/xml-query.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-lib.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-log.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-db.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-search.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-show.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-curl.elc
Wrote /home/dogsleg/freedom/packaging/elpa/elfeed/elfeed-csv.elc
emacs -batch -Q -L . -L tests -l tests/elfeed-tests.el -f ert-run-tests-batch
Running 34 tests (2016-10-12 22:19:51+0500)
   passed   1/34  elfeed-autotags
   passed   2/34  elfeed-clamp
   passed   3/34  elfeed-cleanup
   passed   4/34  elfeed-db-dates
   passed   5/34  elfeed-db-feed-entries
   passed   6/34  elfeed-db-merge
   passed   7/34  elfeed-db-meta
   passed   8/34  elfeed-db-size
   passed   9/34  elfeed-db-tag
   passed  10/34  elfeed-db-upgrade
   passed  11/34  elfeed-db-visit
   passed  12/34  elfeed-directory-empty-p
   passed  13/34  elfeed-entries-from-x
   passed  14/34  elfeed-feed-type
Test elfeed-float-time backtrace:
  (if (unwind-protect (setq value-81743 (apply fn-81741 args-81742)) (
  (let (form-description-81745) (if (unwind-protect (setq value-81743 
  (let ((value-81743 (quote ert-form-evaluation-aborted-81744))) (let 
  (let ((fn-81741 (function null)) (args-81742 (list (elfeed-float-tim
  (progn (let ((fn-81716 (function =)) (args-81717 (list (elfeed-float
  (closure (t) nil (progn (let ((fn-81716 (function =)) (args-81717 (l
  #[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\317\320%DC
  funcall(#[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\31
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  #[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\316%DC\2
  funcall(#[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\
  ert-run-test([cl-struct-ert-test elfeed-float-time nil (closure (t) 
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test e
  ert-run-tests(t #[385 "\306\307\"\203D\211\211G\310U\203\211@\20
  ert-run-tests-batch()
  command-line-1(("-L" "." "-L" "tests" "-l" "tests/elfeed-tests.el" "
  command-line()
  normal-top-level()
Test elfeed-float-time condition:
    (ert-test-failed
     ((should
       (null
	(elfeed-float-time "notadate")))
      :form
      (null 1476292792.1610928)
      :value nil))
   FAILED  15/34  elfeed-float-time
   passed  16/34  elfeed-format-column
   passed  17/34  elfeed-goto-line
   passed  18/34  elfeed-keyword->symbol
   passed  19/34  elfeed-kill-line
   passed  20/34  elfeed-looks-like-url-p
   passed  21/34  elfeed-move-to-first-empty-line
   passed  22/34  elfeed-opml
   passed  23/34  elfeed-readable-p
   passed  24/34  elfeed-ref
   passed  25/34  elfeed-ref-pack
   passed  26/34  elfeed-resize-vector
   passed  27/34  elfeed-slurp-spit
   passed  28/34  elfeed-tagger
   passed  29/34  elfeed-time-duration
   passed  30/34  elfeed-update-location
   passed  31/34  elfeed-valid-regexp-p
   passed  32/34  elfeed-xml-base
   passed  33/34  elfeed-xml-parse-region
   passed  34/34  xml-query

Ran 34 tests, 33 results as expected, 1 unexpected (2016-10-12 22:19:52+0500)

1 unexpected results:
   FAILED  elfeed-float-time`

**Comment by skeeto** [comment]
I'm unable to reproduce with Emacs 24.4.1 on stable, nor with Emacs
24.5.1 in unstable, nor with my own build of Emacs 25.1.1. I suspect
it's a localization thing, and I have an idea for a fix. What's the
result of evaluating this expression?

    (date-to-time "notadate")

On my system it's (14445 17280), which is hardcoded in Elfeed as the
failure return value. If this is the problem, rather than hardcode it I
should just get the error result from a known bad input at run time.

**Comment by dogsleg** [comment]
For me it is as follows:

`Debugger entered--Lisp error: (error "Invalid date: notadate")
  signal(error ("Invalid date: notadate"))
  error("Invalid date: %s" "notadate")
  byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date: %s" date)))] 3)
  date-to-time("notadate")
  eval((date-to-time "notadate") nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)`

**Comment by dogsleg** [comment]
And after starting Elfeed I'm getting `Invalid date: notadate` in Minibuffer when evaluating the expression.

**Comment by skeeto** [comment]
Interesting. So on your system it signal an error if the date is
invalid. I've never seen that before. I wonder what's causing the
difference. Does 323cfe4 pass the tests?

**Comment by dogsleg** [comment]
`Ran 34 tests, 34 results as expected (2016-10-12 23:53:44+0500)`

Thanks!

**Comment by skeeto** [comment]
Great! Thanks for running the tests and discovering this issue.
