### ISSUE TITLE
Images slow elfeed to a crawl

### ISSUE THREAD

**Issue by jabranham** [skeeto/elfeed#182]
Images/gifs in an article slow Emacs/elfeed to a crawl. Even just hitting "n" to go to the next article can take upwards of 5 seconds. Gifs are especially problematic.

**Comment by skeeto** [comment]
This is a known issue with Emacs itself. What's worse, I've found that
SVGs often hard crash Emacs. Elfeed just puts the images in the buffer
and the rest is handled by Emacs. Also, I don't remember if images are
downloaded asynchronously or not, so that may be part of the delay.

**Comment by jabranham** [comment]
Is there an option to disable images by default (and then, hopefully, a command to toggle them on)?

**Comment by skeeto** [comment]
Sorry, I should have mentioned this in my other response. Entry
rendering is done with the built-in package shr (Simple HTML Renderer).
This is undocumented, but currently you can set shr-inhibit-images to
non-nil to disable images.
