### ISSUE TITLE
Autotagging Not Functioning on Emacs 25 on Debian Stretch

### ISSUE THREAD

**Issue by jandrusk** [skeeto/elfeed#186]
Followed instructions on elfeed home page, but custom tags are still not being applied.

The config I applied can be found at:

http://pastebin.com/80UcPMSb

Running Emacs 25.1.1 on Debian Stretch. Attaching screenshot of feed list as well.

![elfeed-no-auto-tags](https://cloud.githubusercontent.com/assets/1035829/21571937/25d01eba-cea2-11e6-8c2a-ac7cb9451c30.png)

**Comment by skeeto** [comment]
Both autotagging and hooks will only apply to newly discovered entries.
You can run the hooks against the existing entries with M-x
elfeed-apply-hooks-now. You might need to press "g" to redraw the
listing afterward.

In your particular situation, the autotagging features, where tags are
expressed alongside the URLs in elfeed-feeds, would completely suffice.
That saves you from messing around with hooks, which is there for more
complicated manipulations. For example, you're already configured to
automatically tag anything from Planet Emacs with "emacs". Just add the
"editors" symbol to that sublist. Same goes for your "theology" tag on
the other feed, which will need to be itself wrapped in its own list.

**Comment by jandrusk** [comment]
Thanks! That's the guidance I needed.
