### ISSUE TITLE
elfeed-db-compact consumes too much memory

### ISSUE THREAD

**Issue by yang-ling** [skeeto/elfeed#191]
Hi. Thanks for this amazing RSS reader. I use it everyday. But this problem, as title says, troubles me much.

I have this line in my config

`(add-hook 'kill-emacs-hook 'elfeed-db-compact)`

When I close emacs, `elfeed-db-compact` will run, and I notice more than 2G memory is consumed. The memory is released once emacs is killed.

I also tried to remove this hook, and manually run `elfeed-db-compact`. Same thing happened, that is more than 2G memory is consumed.

My `archive.gz` is 3.2MB at this moment, and `index` is 1.48MB.

My Laptop only has 4G memory in total, so it becomes unresponsive when `elfeed-db-compact` is running. I have to use `kill -9` to kill emacs process.

Could you help me?

Environment information:

* My OS is Archlinux.
* Emacs version is 25.1.1.
* Spacemacs version is 0.200.7
* Elfeed version is `20161231.735`, installed by `elfeed` layer of Spacemacs

**Comment by skeeto** [comment]
It seem you've somehow accumulated huge entry content. What's the
uncompressed size of archive.gz? Are there any huge files under data/ in
your Elfeed directory?

If it's a problem, just delete archive.gz and the data/ directory. These
only contain raw entry content and will automatically be repopulated for
recent content. All your tags and such are in the index file, which is
the precious part of the database. If the problem returns, then at least
one of the feeds you follow is delivering massive quantities of entry
content.

The problem is that, for compaction, Elfeed processes the entire
uncompressed archive in a single large buffer. It does so in order to
take advantage of auto-compression-mode. It might be worth have an
alternate approach for situations like these.

**Comment by yang-ling** [comment]
Thanks for reply.

> What's the uncompressed size of archive.gz?

`du -shc *` under Elfeed directory result is 8.6MB, and `data` directory size is
7.1MB. I think it is not huge, right?

> Are there any huge files under data/ in your Elfeed directory?

I executed `du -hc -t 100K *` under `data` folder of my Elfeed directory, the
result is there no single file larger than 100K. Most of those files are smaller
than 50KB. So I think there is no huge file.

My feeds are some forum RSS, blog RSS, which are plain text and a few image URLs

I also have some image RSS, which contains nothing but image URLs. One article
contains 1 image URL in most case, a few contains 3 or more URLs, but never more
than 5 image URLs.

I don't know whether image RSS causes this problem.

> If it's a problem, just delete archive.gz and the data/ directory.

Actually I already deleted it 3 weeks ago. At first it is OK because data is
small, but once `archive.gz` is larger than 1MB, I can notice the memory
consumption. It seems that memory consumption is linear with`archive.gz` size.
1MB `archive.gz` will cause nearly 1G memory consumption in db compact process,
and current my `archive.gz` is 3.2MB, which causes more than 2G memory
consumption.

> The problem is that, for compaction, Elfeed processes the entire
> uncompressed archive in a single large buffer. It does so in order to
> take advantage of auto-compression-mode

I think this process logic is fine, but what I feel strange is uncompressed
archive which is smaller than 10MB, consumes more than 2G memory in compaction
process. It doesn't make sense.

my workaround is not compacting db in my old laptop, but in my work PC, which
has 16GB memory, and delete Elfeed data directory every month.

Do you or any others have this issue? Or is it just me? Can you reproduce this
issue in your environment?

**Comment by skeeto** [comment]
It's not something I've seen before, and I can't think of what would
make memory usage blow up so much. All the file sizes you're citing are
reasonable and normal. I really thought you must have had a large
artifact, but that's certainly not the case.

The image links have nothing to do with it. No additional content is
fetched and only the content included in the feed itself is archived.

**Comment by yang-ling** [comment]
It seems it's only me who has the problem.

I plan to install ArchLinux on my new laptop this week. I will check whether this issue happens on my new laptop.

Thanks for your help.
