### ISSUE TITLE
cURL with socks5 proxy: (2) Failed to initialize

### ISSUE THREAD

**Issue by akater** [skeeto/elfeed#193]
Adding extra argument in the form `--socks5-hostname host:port` or `--proxy socks5h://host:port` causes failure to fetch any feeds. The only error message I could get was “(2) Failed to initialize.”

Checked for http feeds and socks5h only. Other socks5h-proxified cURL processes perform fine.

**Comment by skeeto** [comment]
Make sure to provide the information as separate argument strings. Only
when I put them together into the same string do I get your error. No
shell is executed to split the argument string (which also means you
don't need to worry about quoting).

    (setf elfeed-curl-extra-arguments '("--socks5-hostname" "host:port"))

Alternatively, you can use one of curl's environment variables, such as
ALL_PROXY.

    (setenv "ALL_PROXY" "socks5h://host:port")

The latter is my own preference.

**Comment by akater** [comment]
Thanks, that resolved the issue.
