### ISSUE TITLE
[BUG] 100% reproducible emacs crash in elfeed- using emacs -q (backtrace attached)

### ISSUE THREAD

**Issue by zeltak** [skeeto/elfeed#194]
Hi

i have this nasty bug in elfeed (i think) that crashed emacs which i can reproduce 100% of the time. i also tried it with emacs -Q and i can reproduce it as well. im not very technical and followed a guide on how to produce a backtrace (attached in next  message)

this is my minimal conf to reproduce

```
(setq load-prefer-newer t)
;; This sets up the load path so that we can override it
(package-initialize nil)

(setq inhibit-startup-screen t)



(require 'package)


(setq package-enable-at-startup nil
package-archives
'(("gnu"             . "http://elpa.gnu.org/packages/")
("melpa"           . "http://melpa.org/packages/")
;; ("melpa-stable" . "http://stable.melpa.org/packages/")
;; ("elpy"         . "http://jorgenschaefer.github.io/packages/")
("org"          . "http://orgmode.org/elpa/") ;; for org-plus-contrib
))
(package-initialize :noactivate)
(unless (package-installed-p 'use-package)
(package-refresh-contents)
(package-install 'use-package))
(require 'use-package)
;; you can turn this on to see when exactly a package get's configured
;; (setq use-package-verbose t)
(setq custom-file "~/.emacs.d/custom.el")
[macs.bug.report.txt](https://github.com/skeeto/elfeed/files/726494/macs.bug.report.txt)
[macs.bug.report.txt.zip](https://github.com/skeeto/elfeed/files/726495/macs.bug.report.txt.zip)


(load custom-file 'noerror)
; Check if system is windows
(defun system-type-is-win ()
(interactive)
"Return true if system is windows"
(string-equal system-type "windows-nt")
)
;; Check if system is GNU/Linux
(defun system-type-is-gnu ()
(interactive)
"Return true if system is GNU/Linux-based"
(string-equal system-type "gnu/linux")
)
;;;add custom themes to list
(add-to-list 'custom-theme-load-path "/home/zeltak/.emacs.d/themes")
;to load a specifc theme 
;(load-file "~/.emacs.d/themes/zprime-theme.el")
;load the choosen theme at startup 
(load-theme 'zprime t)
(setq org-export-backends (quote (ascii html icalendar latex org)))
(add-to-list 'load-path "/home/zeltak/.emacs.g/org-mode/contrib/lisp/")
; fonts in linux
(if (string= system-name "zx1voics")
;(add-to-list 'default-frame-alist '(font . "Inconsolata-16"))
;(add-to-list 'default-frame-alist '(font . "Source Code Pro-18"))
;(add-to-list 'default-frame-alist '(font . "Pragmata Pro-19"))
;(add-to-list 'default-frame-alist '(font . "Fantasque Sans Mono 14"))
(add-to-list 'default-frame-alist '(font . "fira mono 19"))
)
;; fontso in Win
;(if (system-type-is-win)
;(add-to-list 'default-frame-alist '(font . "Consolas-14"))
;)
(if (string= system-name "zbeast")
(add-to-list 'default-frame-alist '(font . "fira mono 23"))
)
;; backwards compatibility as default-buffer-file-coding-system
;; is deprecated in 23.2.
(if (boundp 'buffer-file-coding-system)
(setq-default buffer-file-coding-system 'utf-8)
(setq default-buffer-file-coding-system 'utf-8))
;; Treat clipboard input as UTF-8 string first; compound text next, etc.
(setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
;; UTF-8 as default encoding
(set-language-environment "UTF-8")
(set-charset-priority 'unicode)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))

(use-package elfeed
:ensure t
:config
;;;default search 
)


(setq elfeed-feeds
'(
;;comics
("http://phdcomics.com/gradfeed.php" comics)
("http://theoatmeal.com/feed/rss" comics)
("http://xkcd.com/rss.xml" comics)
("http://researchinprogress.tumblr.com/rss" comics)
;;uni 
"http://rforpublichealth.blogspot.com/feeds/posts/default" 
;;music
"https://muspy.com/feed?id=f9qypqwxc658e6dbzwk8n9mqthsgv4" 
))
```

Would be very happy to help in trying to debugg this

best

Z

**Comment by zeltak** [comment]
[macs.bug.report.txt.zip](https://github.com/skeeto/elfeed/files/726496/macs.bug.report.txt.zip)

this is the backtrace

**Comment by skeeto** [comment]
What makes it crash? Just starting Emacs? Bringing up the Elfeed search
buffer? What version of Emacs are you using and on what OS?

I don't think this bug has much to do with Elfeed (Elfeed shouldn't be
able to crash Emacs, period) but rather it's a bidi (bi-directional
text) bug in Emacs. The content of one of these feeds is tripping up
functions in bidi.c. From the backtrace, it looks like bidi_cache_find()
is returning UNKNOWN_BT, failing the assertion in bidi_find_bracket_pairs():

      eassert (type == NEUTRAL_ON);

Which then causes the terminate_due_to_signal().

Something in the feed content (title, etc.) is causing Emacs to use bidi
processing, and then runs Emacs into a bad state. I wasn't able to
reproduce the crash (neither in Emacs 24.4, nor 25.1), so unfortunately
I can't narrow the problem down any further. Maybe download the feeds
with curl/wget and try viewing them within Emacs. Try running
xml-parse-region or elfeed-xml-parse-region on the buffer to see if that
crashes Emacs. You could also treat these downloads as file-protocol
feeds (e.g. "file://") to get something reproducible only from local
data.

To avoid MELPA, you can clone the Elfeed repository and run it from
there (emacs -L elfeed/ -l elfeed/elfeed.el). The idea is to narrow it
down to something small that can crash vanilla Emacs without loading any
third-party code.

I suspect it comes down to running a particular search over a particular
sequence of codepoints. Emacs has had bugs like that before.

**Comment by zeltak** [comment]
thx @skeeto 

im updating that this is indeed an emacs bug

http://lists.gnu.org/archive/html/bug-gnu-emacs/2017-01/msg00730.html

which i reported and should be fixed in next emacs release

thx for the help!

Z

**Comment by zeltak** [comment]
another update!

i see its elfeed-goodies which is crashing emacs not elfeed and it does indeed happen with bidi rss entries
