### ISSUE TITLE
elfeed-search-show-entry in other window?

### ISSUE THREAD

**Issue by zeltak** [skeeto/elfeed#195]
Hi!

i was wondering if there was an option to have `elfeed-search-show-entry ` open in new window? i looked in the documentation but couldnt find such an option.

i prefer not to use elfeed-goodies bu rather have a split emacs frame into 2 windows where the left window will be in a elfeed-search mode and the right in a elfeed-show mode and pressing enter in the search mode will open the entry in the right show window?

thx :)

Z

**Comment by skeeto** [comment]
Just set your own function for elfeed-show-entry-switch. It's set to
switch-to-buffer by default.

**Comment by zeltak** [comment]
thx @skeeto !

my lisp coding skills regretfully is zero :) 

you mean something like this

``(setq elfeed-show-entry-switch
      'split-window-right)
```

**Comment by skeeto** [comment]
Close, but it needs to be a function that accepts a single argument,
which is the buffer to be displayed. To use split-window-right, you'd
call it from your own buffer-switching function. For example:

    (setq elfeed-show-entry-switch
          (lambda (b)
            (let ((w (split-window-right 80)))
              (set-window-buffer w b)
              (select-window w))))

If you're familiar with Magit, it's the exact same concept as
magit-display-buffer-function. You can search online for that name to
see how people other people manage this sort of thing.

This might be close to what you're looking for:

    (setq elfeed-show-entry-switch #'pop-to-buffer)
    (define-key elfeed-show-mode-map (kbd "q") #'delete-window)

It uses pop-to-buffer to split and put focus in the new window. It also
redefines "q" in elfeed-show-mode to kill the window that pop-to-buffer
created.

**Comment by zeltak** [comment]
> This might be close to what you're looking for:
>   (setq elfeed-show-entry-switch #'pop-to-buffer)
> (define-key elfeed-show-mode-map (kbd "q") #'delete-window)

Perfect, thx so much and thx again for elfeed, its truly amazing :D 

best

Z
