### ISSUE TITLE
is it possible for elfeed to confirm marking all as read when i issue my ugly wrote function :D

### ISSUE THREAD

**Issue by zeltak** [skeeto/elfeed#197]
Hi

i have this function i wrote

```
(defun z/elfeed-all-read-refresh ()
(interactive)
(elfeed-mark-all-as-read)
(elfeed-search-fetch nil) 
 )
```

now i cant code and i know its very basic but  i was wondering if it is possible to add a confirmation to this function? (keeping in mind i cant code :) )

thx

Z

**Comment by Sodaware** [comment]
Emacs has some built in functions that can be used for this: `yes-or-no-p` and `y-or-no-p`. 

`yes-or-no-p` will prompt the user to type a full `yes` or `no`. `y-or-n-p` will accept just `y` or `n`.

Something like this should do the trick:

```elisp
(defun z/elfeed-all-read-refresh ()
  (interactive)
  (when (y-or-n-p "Really mark all items as read?")
    (elfeed-mark-all-as-read)
    (elfeed-search-fetch nil)))
```

Hope that helps!

**Comment by zeltak** [comment]
awesome, this is perfect @Sodaware !

thx

Z
