### ISSUE TITLE
Error during redisplay: (eval (funcall elfeed-search-header-function)) signaled (no-catch --cl-block-nil-- "239/239:53")

### ISSUE THREAD

**Issue by wdenton** [skeeto/elfeed#205]
I'm getting this error when hitting RET in the feed list: instead of showing me the entry, nothing happens (except this error).

 I problem a few days ago (I didn't record details) which stopped Elfeed from working at all. I guessed was caused by a corrupted ~/.elfeed/index, which I deleted, and then it did run ... but now I can't read any entries.

This is with Emacs compiled from source today, and the current Elfeed.

**Comment by skeeto** [comment]
What's the value of elfeed-search-header-function (a variable)? That's a
strange error message. The thrown string looks like a piece of the
search buffer header, but that shouldn't be thrown. I'm guessing, you've
got a strange function set for the search header function.

**Comment by wdenton** [comment]
Hmm ... its value is "elfeed-search--header." But after upgrading a bunch of packages today, it's all working again! Maybe it's connected to ivy/counsel/swiper, which I use, since ivy adds its own search functions. They all got upgraded to a new version, and maybe something in one of them fixed something. Any road up, it's back to normal, so I'll close this.

Thanks for all the work on Elfeed.
