### ISSUE TITLE
Don’t know how to access metadata

### ISSUE THREAD

**Issue by manuel-uberti** [skeeto/elfeed#207]
Hi,

thanks for elfeed. I'm using latest version from MELPA. Whenever I try to check for updates with <kbd>G</kbd> in `elfeed-search` I get this message:
```
elfeed-meta--plist: Don’t know how to access metadata on [cl-struct-elfeed-feed "http://planet.lisp.org/rss20.xml" "http://planet.lisp.org/rss20.xml" "Planet Lisp" nil (:last-modified "Sat, 08 Apr 2017 04:15:59 GMT" :etag "\"58e863ff-d2b1\"")]
```
If I keep hitting <kbd>G</kbd> the message is displayed for every RSS feed I set up in my elfeed configuration.

I am using GNU Emacs 26.0.50 (commit 449bc49), on Ubuntu 16.04.2 LTS.

**Comment by manuel-uberti** [comment]
To expand a bit on this. I reinstalled elfeed, and upon issuing `elfeed` I get this message:
```
avl-tree-mapc: Wrong type argument: avl-tree-, [cl-struct-avl-tree- [[[[[[[[[nil nil ... 0] nil ("planet.emacsen.org" . "http://irreal.org/blog/?p=6124") -1]
...
```
(I removed all the urls to make it shorter)

**Comment by skeeto** [comment]
Are you running a bleeding edge version of Emacs? If so, I suspect the
Emacs devs have broken all the defstruct tags, and structures serialized
before the change have all been broken. 

If this is the case, then that's pretty annoying because I'll have to
figure out detect and convert the defstruct format. It also means
cl-defstruct isn't reliable part of Emacs, and I'll have to stop using
it. After all, they could break it again any time in the future.

As a workaround you could try deleting (or moving) your Elfeed "index"
file and starting fresh. Hopefully the new structures can still be
serialized.

**Comment by manuel-uberti** [comment]
Yes, I am following Emacs development, built it last night.

I created my .emacs.d from scratch following a commit on `package.el`, so the old Elfeed index file is not present anymore.

**Comment by skeeto** [comment]
Note that the index file is under "elfeed-db-directory" which, in its
default setting, is not under .emacs.d/. It's also vital that Elfeed is
compiled with the exact version of Emacs that you're running, which it
sounds like you're doing correctly. After purging the index file and
recompiling Elfeed, everything seems to work fine for me.

The following is more of a note for myself, but I just built the lastest
Emacs and here's how it changed:

    ;; Emacs 25.1 and earlier:
    (avl-tree-create #'<)
    [cl-struct-avl-tree- [nil nil nil 0] <]
    
    ;; Beyond Emacs 25.1:
    (avl-tree-create #'<)
    #s(avl-tree- [nil nil nil 0] <)

It looks like structures still have the same serialization properties,
and it's just the format that changed. I'll have to think about how to
deal with this.

**Comment by manuel-uberti** [comment]
Purging index and reinstalling Elfeed fixed. Thank you for your kind help!

**Comment by skeeto** [comment]
I'm reopening this issue since the fundamental problem hasn't been solved yet.

**Comment by manuel-uberti** [comment]
Any updates on this one?

Elfeed is working fine now, just curious :relaxed:

**Comment by aplaice** [comment]
FWIW, The following extremely barbaric elisp expression (to be evaluated (`M-:`) in the buffer corresponding to the elfeed index), worked for me, when migrating my elfeed configuration from emacs-24 to emacs-26 (from git):

```elisp
(progn
  (goto-char (point-min))
  (while (search-forward "cl-struct-" nil t 1)
    (delete-backward-char 10)
    (backward-char 1)
    (save-excursion 
      (forward-list)
      (delete-backward-char 1)
      (insert ")"))
    (delete-char 1)
    (insert "#s(")))
```

[Please back things up before trying.]

I am not sure whether this will work reliably, so I have not converted into a nice function that will open the relevant buffer etc. for you.

I hope that this will be helpful to someone with this issue.

Thank you for elfeed! :)

**Comment by skeeto** [comment]
I haven't taken any time to write a database conversion routine yet. If 
I hear about a looming Emacs 26 release date, it might push me into 
getting this done. Right now I'm concerned about fixing it, then having 
the Emacs devs change something again before release that makes me have 
to fix it again. If you're running a bleeding edge version of Emacs, you 
should be prepared for some breakage like this, so it's only a moderate 
priority at the moment. It will happen eventually.

@aplaice's brute-force text replacement code will generally work, though 
it will corrupt any metadata that happens to include the string 
"cl-struct-". That's not a big deal for entry and feed titles, but it 
would be pretty bad if an entry ID happens to contain this string, which 
it certainly could.

**Comment by defphil** [comment]
Same problem on 26.1 RC1...
