### ISSUE TITLE
Symbol's function definition is void: elfeed-link-store-link

### ISSUE THREAD

**Issue by ReichKV** [skeeto/elfeed#208]
After upgrading to new elfeed I start emacs and get following mistake:

Warning (initialization): An error occurred while loading ‘/home/r/.emacs.d/init.el’:  Symbol's function definition is void: elfeed-link-store-link .. .... . .

(if i comment (use-package elfeed) i still get this error. I dont see the error only if remove elfeed.)

How to solve this problem?

**Comment by skeeto** [comment]
Ah, crap, sorry. This has to do with merging #206 this morning. The
problem is that the new autoload doesn't actually load elfeed-link. You
can work around this manually for the moment by temporarily adding this
to your init before either Elfeed or Org is loaded:

    (require' elfeed-link)

I need to figure out how to load elfeed-link without firing the
eval-after-load twice.

**Comment by ReichKV** [comment]
Thank you, the new update works.

**Comment by skeeto** [comment]
Thanks for following up!
