### ISSUE TITLE
elfeed-entry buffer not showing XKCD graphics 

### ISSUE THREAD

**Issue by heikkil** [skeeto/elfeed#218]
Some time ago graphics from XKCD stopped showing graphics in my elfeed-entry buffer. Only the title text is shown.

I am using the atom feed: http://xkcd.com/atom.xml

**Comment by skeeto** [comment]
Perhaps you switch to a build of Emacs that doesn't support images? That 
feed is working correctly on my end. Do you see an image when you 
evaluate this in your scratch buffer?

    (shr-insert-document
     '(img ((src . "https://www.gnu.org/graphics/bokma-emacs.png"))))

This is the same mechanism (shr) that Elfeed uses for feed images.

**Comment by cadadr** [comment]
Hi!

On 2017-05-19 04:24 +07, Christopher Wellons <notifications@github.com> wrote:
> Perhaps you switch to a build of Emacs that doesn't support images? That 

I can confirm that XKCD images failed to display in Elfeed on my Emacs
too, until recently, and my build does support images.  I could use EWW
to load the page to see the image.  But since today they do load
normally.  Maybe it was a temporary problem on the server side?

> feed is working correctly on my end. Do you see an image when you 
> evaluate this in your scratch buffer?
>
>     (shr-insert-document
>      '(img ((src . "https://www.gnu.org/graphics/bokma-emacs.png"))))
>
> This is the same mechanism (shr) that Elfeed uses for feed images.

**Comment by heikkil** [comment]
It was the problem with graphics support. Thanks.

I am on a Mac. Homebrew has started complaining about not being able to create proper Mac OS X packages and recommended using the 'brew cask' that is for GUI programmes. The emacs from brew cask is a wrapper around package from https://emacsformacosx.com/. It does not have graphics support.

I recompiled the standard emacs keg with '--with-imagemagick@6' (the latest v. 7 does not work) and graphics display and scaling works again.

**Comment by skeeto** [comment]
Thanks for following up with the details! I'm sure someone will find 
this information useful in the future when they're having the same 
problem.
