### ISSUE TITLE
Is there a way to resize graphics in elfeed-entry buffer?

### ISSUE THREAD

**Issue by heikkil** [skeeto/elfeed#219]
Two comics feeds from the same source changed recently the image size. Now just over half of the strip is visible in elfeed-entry and I do not seem to be able to scroll right nor resize the images.

These are the feeds:
http://kimmo.suominen.com/stuff/vw.xml
http://kimmo.suominen.com/stuff/fingerpori.xml

Is there a(n easy) fix?

**Comment by skeeto** [comment]
All of the HTML rendering is done by Emacs' built-in shr package, so any 
configuration you're looking for would be for shr. Browse through its 
customizations to see if anything stands out. For example, you might 
want to take a look at shr-max-image-proportion.

**Comment by heikkil** [comment]
Turned out this was an other aspect of lack of graphics support in my emacs. Emacs compiled with imagemagick scales graphics transparently. See #218 for more details.
