### ISSUE TITLE
Error message on elfeed-add-feed on OS X

### ISSUE THREAD

**Issue by sgtpep** [skeeto/elfeed#22]
First of all, thank you for your great alternative feed reader. It seems like minimalistic newsbeuter done right. Second, I'm totally noob to Emacs, and try using its great addons before I learnt the editor itself.

When I call elfeed-add-feed function the error message says "Symbol's function definition is void: x-get-selection-value". Maybe it's because of the absence of X11-related functions on Emacs for OS X.

**Comment by oystersauce8** [comment]
This issue can probably be closed now.
Upgrading to elfeed >= 2.0.1 should resolve the issue, because it includes commit d54bc55)

**Comment by skeeto** [comment]
Closed by d54bc55. Thanks, @oystersauce8.
