### ISSUE TITLE
(wrong-type-argument cl--random-state [cl--random-state-tag -1 30 7459106193552])

### ISSUE THREAD

**Issue by manuel-uberti** [skeeto/elfeed#227]
Hi,

I am using GNU Emacs 26.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9), commit `903c874` to be more precise.

When I press `G` in the `*elfeed-search*` buffer, I get this error:
```
Debugger entered--Lisp error: (wrong-type-argument cl--random-state [cl--random-state-tag -1 30 7459106193552])
  signal(wrong-type-argument (cl--random-state [cl--random-state-tag -1 30 7459106193552]))
  cl-random(10)
  elfeed--shuffle(("http://planet.emacsen.org/atom.xml" "http://planet.lisp.org/rss20.xml" "http://planet.clojure.in/atom.xml" "http://www.scheme.dk/planet/atom.xml" "https://cavallette.noblogs.org/feed" "https://tacticaltech.org/rss.xml" "http://dilbert.oeey.com/" "http://www.commitstrip.com/en/feed/" "http://www.savagechickens.com/feed" "http://reverseshot.org/archive/entry/rss"))
  elfeed-update()
  elfeed-search-fetch(nil)
  funcall-interactively(elfeed-search-fetch nil)
  call-interactively(elfeed-search-fetch nil nil)
  command-execute(elfeed-search-fetch)
```

**Comment by skeeto** [comment]
This is a bug in the Emacs master branch at the moment:

    $ emacs -Q --batch -l cl-lib --eval '(cl-random 10)'
    Wrong type argument: cl--random-state, [cl--random-state-tag -1 30 7457648982330]

Looks like they're currently mixing up the old defstruct with the new 
Emacs 26 defstruct. You can use that one-liner above to find/bisect a 
version of Emacs without this bug.

**Comment by manuel-uberti** [comment]
Thank you. Let's close this issue then, since it is not related to Elfeed.

**Comment by skeeto** [comment]
Since it's still an issue, I opened up an Emacs bug report (#27617): 
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27617

**Comment by manuel-uberti** [comment]
Thank you very much for this, hope they'll fix it soon.

**Comment by kmicu** [comment]
If some Elfeed user does not want to wait for a fix add `(setq cl--random-state (cl--make-random-state (cl--random-time)))` to your init file and you will be able to use Elfeed again with Emacs' master.
(Also… type system would catch that regression easily 🤓 me *ducks*)

**Comment by manuel-uberti** [comment]
@kmicu thank you for the tip.

**Comment by manuel-uberti** [comment]
@skeeto just a quick update: it has been fixed now on master.
