### ISSUE TITLE
cl-random error

### ISSUE THREAD

**Issue by sjLambda** [skeeto/elfeed#228]
I'm now getting this new error message with G, elfeed-search-fetch:

cl-random: Wrong type argument: cl--random-state, [cl--random-state-tag -1 30 7458138833218]

Elfeed is from melpa, Version 2.1.1 on emacs compiled from sources, version GNU Emacs 26.0.50.

**Comment by skeeto** [comment]
This is an Emacs bug on the master branch at the moment. See #227. I don't see any bug reports to the Emacs devs about this, so they still might not even be aware of it.
