### ISSUE TITLE
cant get coloring by tag to work (change face)

### ISSUE THREAD

**Issue by zeltak** [skeeto/elfeed#231]
Hi

I tried to follow some online examples on how to get the coloring to work but cant seem to be able to get this to work

this is my current config part

```
 ;; different face colors for different kinds of content (videos, podcast, comics)
  ;; Mapping of tags to faces in the Elfeed entry listing.


  (defface read-elfeed-entry
    '((t :foreground "#E2e2e2"))
    "Marks a read link")
  (push '(read read-elfeed-entry)
        elfeed-search-face-alist)

  (defface semacs-elfeed-entry
    '((t :foreground "SteelBlue"))
    "Marks a semacs link")
  (push '(read semacs-elfeed-entry)
        elfeed-search-face-alist)



  (defface remacs-elfeed-entry
    '((t :foreground "#A9383D"))
    "Marks a remacs link")
  (push '(read remacs-elfeed-entry)
        elfeed-search-face-alist)

  (defface femacs-elfeed-entry
    '((t :foreground "tomato"))
    "Marks a femacs link")
  (push '(read femacs-elfeed-entry)
        elfeed-search-face-alist)
```

i have entries tagged semacs, femacs etc, yet they dont get colored and the face dosent change

any clue whats im missing?

thx

Z

**Comment by skeeto** [comment]
As you might guess from the name, elfeed-search-face-alist is an 
association list (alist). It's in the exact same format expected by 
assoc and friends. The car of each sublist is the key and the cdr is the 
value. If there are repeat entries, only the first in the list will be 
used.

For example, after evaluating your code, your elfeed-search-face-alist 
will look like this:

    ((read femacs-elfeed-entry)
     (read remacs-elfeed-entry)
     (read semacs-elfeed-entry)
     (read read-elfeed-entry)
     (unread elfeed-search-unread-title-face))

When Elfeed needs to find the faces for the "read" tag:

    (cdr (assoc 'read elfeed-search-face-alist))
    ;; -> (femacs-elfeed-entry)

And if it looks up the "semacs" tag:

    (cdr (assoc 'semacs elfeed-search-face-alist))
    ;; -> nil

It looks like your mistake is using "read" multiple times instead if 
"semacs", "remacs", etc. Change "read" in each push.

**Comment by zeltak** [comment]
oops yeah know i see the error :D 

thx alot!

Z
