### ISSUE TITLE
lots of wrong-number-of-arguments errors in *elfeed-log*

### ISSUE THREAD

**Issue by jkitchin** [skeeto/elfeed#239]
I am seeing a lot of errors like this one in my log file:

[2017-09-18 14:41:14] [error]: http://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1521-3773: (wrong-number-of-arguments #[(strings &optional paren) \306 \307\216\310\211\311\211
;\203
\202
\205\312\313\314\315!\316"!\317\2061\320?#
\321=\203E\322\323Q\202U
\324=\203S\325\326Q\202U.	\207 [save-match-data-internal max-lisp-eval-depth max-specpdl-size completion-ignore-case completion-regexp-list paren match-data #[nil \301\302"\207 [save-match-data-internal set-match-data evaporate] 3] 10000 nil \( delete-dups sort copy-sequence string-lessp regexp-opt-group t words \< \> symbols \_< \_> open strings sorted-strings re] 5 1827349] 29)

I am not sure if this is something I have done or not. Some of my feeds update fine, but not all of them. Any thoughts on what could be causing that?

**Comment by skeeto** [comment]
I wonder if you've got your byte-compiled files crossed somehow: .elc 
files compiled with a different version of Emacs, or .elc files compiled 
while having an older version of Elfeed loaded (a long-standing flaw of 
package.el). This feed is working fine on my end in a bare Emacs config 
and an empty Elfeed repository. Try reinstalling/recompiling Elfeed from 
scratch.

The function being called with the wrong number of arguments—the one 
whose bytecode appears in the error message—is regexp-opt. Elfeed 
doesn't call this function, at least not directly. This suggests maybe 
something is even miscompiled in your Emacs installation, or maybe it's 
another package that's misbehaving (advice, hook, etc.).

**Comment by jkitchin** [comment]
Doh! Thanks for the pointer to regexp-opt, I was calling it incorrectly in a scoring function. elfeed works fine!
