### ISSUE TITLE
how to change key bindings in *elfeed-entry*

### ISSUE THREAD

**Issue by pengpengxp** [skeeto/elfeed#240]
I want to change keybindgins in *elfeed-entry*.

But I can not find any map look-like "elfeed-entry-mode-map" . And I have changed "elfeed-show-mode-map",  it seems not working.

By the way, in *elfeed-entry*, RET bind to newline normally. But when I move my cursor on a url, it bind to shr-browse-url. I really don't know why. I grep all the elfeed code. only find shr-brose-url in elfeed-show-mode-map:
```
(defvar elfeed-show-mode-map
  (let ((map (make-sparse-keymap)))
    (prog1 map
      (suppress-keymap map)
      (define-key map "d" 'elfeed-show-save-enclosure)
      (define-key map "q" 'elfeed-kill-buffer)
      (define-key map "g" 'elfeed-show-refresh)
      (define-key map "n" 'elfeed-show-next)
      (define-key map "p" 'elfeed-show-prev)
      (define-key map "s" 'elfeed-show-new-live-search)
      (define-key map "b" 'elfeed-show-visit)
      (define-key map "y" 'elfeed-show-yank)
      (define-key map "u" (elfeed-expose #'elfeed-show-tag 'unread))
      (define-key map "+" 'elfeed-show-tag)
      (define-key map "-" 'elfeed-show-untag)
      (define-key map (kbd "SPC") 'scroll-up-command)
      (define-key map (kbd "DEL") 'scroll-down-command)
      (define-key map "\t" 'shr-next-link)
      (define-key map [tab] 'shr-next-link)
      (define-key map "\e\t" 'shr-previous-link)
      (define-key map [backtab] 'shr-previous-link)
      (define-key map [mouse-2] 'shr-browse-url)
      (define-key map "A" 'elfeed-show-add-enclosure-to-playlist)
      (define-key map "P" 'elfeed-show-play-enclosure)))
  "Keymap for `elfeed-show-mode'.")
```
As it shown, it binds to [mouse-2] other than RET. 

I run describe-function when my cursor is under a url in *elfeed-entry* buffer:
```
shr-browse-url is an interactive compiled Lisp function in `shr.el'.

It is bound to RET, v, <mouse-2>.

(shr-browse-url &optional EXTERNAL MOUSE-EVENT)

Browse the URL under point.
If EXTERNAL, browse the URL using `shr-external-browser'.

[back]
```
Where do the RET and v bind? I can't find in the code.

**Comment by skeeto** [comment]
Entries are displayed with elfeed-show-mode, so elfeed-show-mode-map is 
definitely what you're looking for. If your changes to this map don't 
seem to be working it could be that you're setting it incorrectly. 
Here's an example that adds vi-style scrolling:

    (define-key elfeed-show-mode-map "k" (elfeed-expose #'scroll-down 1))
    (define-key elfeed-show-mode-map "j" (elfeed-expose #'scroll-up 1))

I think the RET binding that you're looking for is in shr-map. In the 
Emacs source it's bound using "\r" rather than RET. The strangeness of 
the links has to do with them being "buttons" or something like that, 
with special behavior attached by shr.

**Comment by pengpengxp** [comment]
Yes, I change the `shr-map'. It works now. Thank you very much.
