### ISSUE TITLE
index is a large file, open literally to avoid performance issue

### ISSUE THREAD

**Issue by sebhahn** [skeeto/elfeed#255]
When I close emacs I always get a notification saying/asking:

`/path/to/index is a large file, open literally to avoid performance issues?`

Is it possible to turn this message off? Is it possible to reset/delete the index file?

**Comment by skeeto** [comment]
It looks like this warning comes from spacemacs/check-large-file rather 
than from Emacs. So you need to set dotspacemacs-large-file-size? I 
don't use Spacemacs, so I don't know for sure.

**Comment by divansantana** [comment]
So to fix this I tried adding `elfeed-search-mode` to
`spacemacs-large-file-modes-list` like so:

```lisp
spacemacs-large-file-modes-list '(archive-mode tar-mode jka-compr git-commit-mode image-mode doc-view-mode doc-view-mode-maybe ebrowse-tree-mode pdf-view-mode elfeed-search-mode)
```

Unfortunately this doesn't resolve it for me. So I set this which is not ideal,
but does the job.


```lisp
dotspacemacs-large-file-size 2
```

**Comment by sebhahn** [comment]
@divansantana thanks!!
