### ISSUE TITLE
elfeed-new-entry-hook reset when "elfeed" is run?

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#256]
Hi Chris,

I've noticed that `elfeed-new-entry-hook` is being reset to nil when I run `elfeed`.  I've checked the source for `elfeed-goodies`, `elfeed`, and the Elfeed-related code in my own config, but I can't find anything that changes the variable except the initial `defvar` and calls to `add-hook`.  Do you have any idea what might be going on?

Thanks.

**Comment by skeeto** [comment]
I can't see anything that would be setting or changing this variable. 
It's defined with defvar, which won't rebind the variable if it's 
already bound. And otherwise it's only accessed twice, both times in a 
cl-loop "for" expression.

**Comment by alphapapa** [comment]
Right, that's what I saw too.  I guess it must be a problem hiding in my config somewhere.  I'll go ahead and close this. Thanks for your help, sorry for taking up your time on this.

**Comment by alphapapa** [comment]
I finally discovered that this is caused by `elfeed-org`: https://github.com/remyhonig/elfeed-org/issues/34

**Comment by skeeto** [comment]
Thanks for the followup!
