### ISSUE TITLE
Provide ability to not send User-Agent header

### ISSUE THREAD

**Issue by davemq** [skeeto/elfeed#257]
I'm trying to use elfeed to read some internal Atom feeds. I constantly got a "403" response from this particular server. I tried running `curl` by hand, and it worked fine. So I started adding the same arguments generated by `elfeed-curl--args`. The one that barfed was '-HUser-Agent: Emacs Elfeed 2.2.0'.

As an experiment, I modified `elfeed-with-fetch` to set headers to nil, byte compiled and loaded, and hit "G" to update feeds. Boom, it worked.

I can, and will, advise the function calling `elfeed-curl--args` to not include the User-Agent header, but it would be nice if there was an option to not send the User-Agent header. I'm sure the server side is broken, but I don't hold out much hope of getting it fixed.

**Comment by skeeto** [comment]
You can set elfeed-user-agent to a custom string, and Elfeed will do the 
right thing. You might just try setting it back to what curl would do by 
default.

As for eliminating the user agent header altogether, it looks like you 
can do this in curl with -H, where the "value" part of the header is 
missing: '-HUser-Agent:'. Do this with elfeed-curl-extra-arguments. 
Everything in that list comes after Elfeed's own arguments, allowing you 
to override them. However, having no user agent header might be just as 
much of a problem as having one the server doesn't recognize.

**Comment by davemq** [comment]
A little searching for User-Agent in the `curl` man page on my RHEL 7.4 system pointed me to setting this header to "Mozilla/4.0", which I assume is the default that `curl` uses. I set `elfeed-user-agent` to "Mozilla/4.0" and my feeds started working. Excellent! Thanks for the pointer!

**Comment by skeeto** [comment]
If you have netcat installed, you can see the default curl request 
yourself really easily. First start a fake web server. I chose port 
8000 for this:

    $ nc -lp 8000

Then run curl against it:

    $ curl http://localhost:8000/

On my system I get the following output from netcat:

    GET / HTTP/1.1
    Host: localhost:8000
    User-Agent: curl/7.52.1
    Accept: */*

**Comment by alphapapa** [comment]
`curl -v` also displays headers in both directions.
