### ISSUE TITLE
Links without protocol are unusable

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#259]
Hi Chris,

I noticed that one of my feeds has started using links without specifying the protocol, e.g.:
```
<item>
        <title>title</title>
        <description><![CDATA[ description.]]></description>
        <link>//www.example.com/article.html</link>
        <guid isPermaLink="false">127968</guid>
        <category>category</category>
        <pubDate>Tue, 12 Dec 2017 00:00:00 -0600</pubDate>
</item>
```
AFAIK this is legal in HTML, and the browser is supposed to use whatever protocol the parent document was fetched with.  But when I try to visit these links, like in w3m or eww or an external browser, they can't handle the link without a protocol.

Of course I can solve this with a new-entry hook, but it seems like elfeed should handle this natively.  What do you think?

Thanks.

**Comment by skeeto** [comment]
Thanks, I haven't run into this sort of thing myself, but I could 
totally see it happening. I think feeds that do this are broken, but I'm 
not opposed to Elfeed accepting and fixing broken feeds when it's easy 
and unambiguous to do so.

**Comment by alphapapa** [comment]
Thank you very much!
