### ISSUE TITLE
Wrong date for old entries newly added?

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#279]
Hi Chris,

A few days ago I added your blog feed, http://nullprogram.com/feed/, to my Elfeed config.  Looking at my list now, I see that some of your old articles are showing up with a date of today.  For example:

```xml
<entry>
  <title>Options for Structured Data in Emacs Lisp</title>
  <link rel="alternate" type="text/html" href="http://nullprogram.com/blog/2018/02/14/"/>
  <id>urn:uuid:3837b5b2-0aba-3381-ff6f-9432f8ff03e9</id>
  <updated>2018-02-14T17:43:34Z</updated>
  <category term="emacs"/>
  <category term="elisp"/>
  <content type="html">...</content>
</entry>
```

When I put the cursor on that item in the elfeed-search buffer and run this code:

```el
(format-time-string "%Y-%m-%d" (elfeed-entry-date (car (elfeed-search-selected))))
```
I get `"2018-06-01"`.  The raw value is:
```el
(elfeed-search-selected)
;; =>
;; [cl-struct-elfeed-entry
;;  ("nullprogram.com" . "urn:uuid:3837b5b2-0aba-3381-ff6f-9432f8ff03e9")
;;  "Options for Structured Data in Emacs Lisp" "http://nullprogram.com/blog/2018/02/14/"
;;  1527901873.3287957
;;  [cl-struct-elfeed-ref "0d5f8c0e684e1efb56a6ff8236f56fb56ef770f0"]
;;  html
;;  nil
;;  (Emacs computers programming starred tech unread)
;;  "http://nullprogram.com/feed/" ...]
```
I did apply the `starred` tag to it, but as far as I can tell from looking at the code, that should not change the entry's date.

From looking at the `elfeed-entries-from-atom` function, it looks like it should get the correct date:

```el
...
(date (or (xml-query* (published *) entry)
          (xml-query* (updated *) entry)
          (xml-query* (date *) entry)
          (xml-query* (modified *) entry) ; Atom 0.3
          (xml-query* (issued *) entry)))
```

Do you have any ideas?  I wonder if I did something wrong.

Thanks for your work on Elfeed.

**Comment by skeeto** [comment]
I'm not able to reproduce this issue with either Emacs 25.1 or Emacs 
26.1 on Linux running the latest version of Elfeed. Try it out in a 
fresh, default Emacs config:

$ export EMACS=emacs   # or whatever version you're testing
$ make clean
$ make -e check        # make sure tests pass
$ mkdir tmp
$ HOME=$PWD/tmp $EMACS -L . -l elfeed.elc -f elfeed -f elfeed-add-feed

If that works, maybe it's something in your configuration.

**Comment by alphapapa** [comment]
Hi again,

Well, I am stumped: I reproduced the problem in Emacs 25 and Emacs 26, with my personal config, with `emacs -q` evaluating the following code, and with the recipe you provided.

```el
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(require 'elfeed)
(setq elfeed-db-directory (make-temp-file "elfeed-debug" 'dir))
(setq elfeed-feeds '(("http://nullprogram.com/feed/" tech computers programming Emacs)))
;; Then:
;; 1.  M-x elfeed RET 
;; 2.  "G"
```
The resulting list is always:
```
2018-06-12 Two Chaotic Motion Demos                                        null program (Emacs,computers,programming,tech,unread)
2018-06-12 Emacs Lisp Lambda Expressions Are Not Self-Evaluating           null program (Emacs,computers,programming,tech,unread)
2018-06-12 A Crude Personal Package Manager                                null program (Emacs,computers,programming,tech,unread)
2018-06-12 Blast from the Past: Borland C++ on Windows 98                  null program (Emacs,computers,programming,tech,unread)
2018-06-12 When the Compiler Bites                                         null program (Emacs,computers,programming,tech,unread)
2018-06-12 When FFI Function Calls Beat Native C                           null program (Emacs,computers,programming,tech,unread)
2018-06-12 Emacs 26 Brings Generators and Threads                          null program (Emacs,computers,programming,tech,unread)
2018-06-12 Minimalist C Libraries                                          null program (Emacs,computers,programming,tech,unread)
End of entries.
```
And in my personal config, those entries (and others) seem to continue to be pulled forward to the present day when I run `elfeed-update`.

I keep my entire `~/.emacs.d` in git, including `elpa`, and I've looked again at my recent commits, and I can't find anything that could have caused this, nor anything even related to Elfeed around the time I posted this issue.

Maybe I'm missing or forgetting something obvious, but so far I'm really stumped.  Thanks for your help.

**Comment by alphapapa** [comment]
Also, all of the tests passed when I ran your recipe.  Thanks.

**Comment by skeeto** [comment]
This seems like it's a date parsing issue with your particular build of 
Emacs. What operating system are you using and where did you get your 
Emacs build? What do each of these evaluate to?

(elfeed-float-time "2018-06-10T01:40:16Z") 
(date-to-time "2018-06-10T01:40:16Z")
(parse-time-string (timezone-make-date-arpa-standard "2018-06-10T01:40:16Z"))
(timezone-make-date-arpa-standard "2018-06-10T01:40:16Z")
(parse-iso8601-time-string "2018-06-10T01:40:16Z")

They results for each *should* be:

1528594816.0
(23324 33152)
(16 40 21 9 6 2018 nil nil -14400)
"09 Jun 2018 21:40:16 -0400"
(23324 33152)

I expect a few of these will not work correctly.

**Comment by skeeto** [comment]
Since you've said it passes the tests, date parsing can't be it since 
the ERT tests include date parser tests. The unit tests even include 
entire sample feeds, and the dates must all be parsed correctly if the 
tests are passing.

So… maybe it's something on your network interfering with the feed? That 
would be strange, but that's the only reason I can imagine for the local 
tests passing but actual feed dates going wrong. On the other hand, you 
included a sample of the feed and it looks fine. Where did you copy that 
XML from? Your web browser? Maybe try downloading it with curl and 
checking it there.

Does the same thing happen when you use my HTTPS feed?

https://nullprogram.com/feed/

**Comment by alphapapa** [comment]
Wow, this keeps getting stranger:
```el
;; Emacs 25.2 -q

(elfeed-float-time "2018-06-10T01:40:16Z")  ;; => nil
(date-to-time "2018-06-10T01:40:16Z")  ;; => (14445 17280)
(parse-time-string (timezone-make-date-arpa-standard "2018-06-10T01:40:16Z"))  ;; => (0 0 18 31 12 1999 nil nil -21600)
(timezone-make-date-arpa-standard "2018-06-10T01:40:16Z")  ;; => "31 Dec 1999 18:00:00 -0600"
(parse-iso8601-time-string "2018-06-10T01:40:16Z")  ;; => (23324 51152)
```
```el
;; Emacs 26.1 -q

(elfeed-float-time "2018-06-10T01:40:16Z")  ;; => nil
(date-to-time "2018-06-10T01:40:16Z") ;; date-to-time: Invalid date: 2018-06-10T01:40:16Z
(parse-time-string (timezone-make-date-arpa-standard "2018-06-10T01:40:16Z"))  ;; let*: Symbol’s function definition is void: string-to-int
(timezone-make-date-arpa-standard "2018-06-10T01:40:16Z") ;; let*: Symbol’s function definition is void: string-to-int
(parse-iso8601-time-string "2018-06-10T01:40:16Z")  ;; => (23324 33152)
```
> This seems like it's a date parsing issue with your particular build of Emacs.  What operating system are you using and where did you get your Emacs build? 

That would be really, really weird.  I'm on Ubuntu 14.04, and I built Emacs 25 and 26 from source myself.  I have *not* updated either of them since before this problem began.

Using the HTTPS URL did the same thing: running the code after midnight now, all of the items showed up for June 13th.

The only possibility I can think of now is that an underlying library that Emacs uses got updated through Ubuntu package updates and introduced a bug, but that would be really weird.

Thanks for your help with this.

**Comment by alphapapa** [comment]
> Where did you copy that XML from? Your web browser? 

IIRC from Chrome's inspector tool.

> Maybe try downloading it with curl and checking it there.

```sh
$ curl https://nullprogram.com/feed/ 2>/dev/null | grep "<updated>"
  <updated>2018-06-10T21:18:50Z</updated>
    <updated>2018-06-10T01:40:16Z</updated>
    <updated>2018-05-31T17:45:16Z</updated>
    <updated>2018-05-27T20:03:15Z</updated>
    <updated>2018-05-01T23:28:06Z</updated>
    <updated>2018-04-13T20:01:31Z</updated>
    <updated>2018-03-27T02:10:35Z</updated>
    <updated>2018-02-22T21:30:57Z</updated>
    <updated>2018-02-15T04:18:07Z</updated>
```
I'm at a loss...

**Comment by skeeto** [comment]
I compiled both Emacs 25.3 and Emacs 26.1 on both Ubuntu 14.04 i686 and 
amd64, each fully up to date. I am still unable to reproduce this issue 
on any of those four combinations. When compiling, I configured Emacs 
like so (replacing VERSION with 25 or 26 as appropriate):

./configure --prefix=$HOME/VERSION --without-all --without-x --with-xml2

All the unit tests passed, all those date parsing samples worked 
correctly, and my own feed worked just fine. I included i686 in case it 
was some sort of integer overflow issue, but it seems to be just fine 
under 32-bit Emacs. (I hardly ever touch 32-bit systems these days, so 
something like that could slip by.)

However, in no cases did I install Elfeed through MELPA. When you ran 
the "emacs -q" test, did you actually set the HOME environment to that 
temporary directory? I ask because you indicated that you used your 
personal config (which is exactly what "-q" is intended to avoid), set a 
different Elfeed database directory (unnecessary, as it would already 
use the temporary directory), and you probably installed Elfeed via 
MELPA (necessary, and also defeats the purpose of the test). That's 
what, in my instructions, the "-L . -l elfeed.elc" was all about: so you 
don't need to install Elfeed. Changing HOME to a temporary directory is 
like creating a blank "Emacs profile" for tests.

This is very important since you could have a stale or miscompiled 
package in your elpa/ directory — a *very* common issue with package.el, 
and why I don't personally use it. This is almost certainly the case if 
you switch back and forth between different versions of Emacs. That's 
unsupported by package.el and you *will* have silently broken packages. 
(This is what Cask fixes.) The fact that the unit tests all pass, but 
Elfeed doesn't work when you initialize package.el is a strong indicator 
that this is the case.

Elfeed has no third-party dependencies, so it's trivial to run it in 
place from the Git repository for these sorts of tests. We don't want to 
initialize package.el and allow it to contaminate Emacs with potentially 
broken third-party packages.

**Comment by alphapapa** [comment]
Hi again,

Well, I thought that I ran your recipe without loading my package.el packages, but I couldn't remember for sure, so I ran it again.  Here's the file that I just ran:

```sh
#!/bin/bash

export EMACS=emacs25   # or whatever version you're testing
make clean
make -e check        # make sure tests pass

tmpdir=$(mktemp -d)

ln -s ~/.Xauthority $tmpdir

export HOME=$tmpdir
$EMACS -L . -l elfeed.elc -f elfeed --eval '(progn (elfeed-add-feed "https://nullprogram.com/feed/") (elfeed-update))'
```

The elfeed-search buffer then looks like this:

```
2018-06-14 Two Chaotic Motion Demos                 null program (unread)
2018-06-14 Emacs Lisp Lambda Expressions Are Not Se null program (unread)
2018-06-14 A Crude Personal Package Manager         null program (unread)
2018-06-14 Blast from the Past: Borland C++ on Wind null program (unread)
2018-06-14 When the Compiler Bites                  null program (unread)
2018-06-14 When FFI Function Calls Beat Native C    null program (unread)
2018-06-14 Emacs 26 Brings Generators and Threads   null program (unread)
2018-06-14 Minimalist C Libraries                   null program (unread)
End of entries.
```

I also ran it with `emacs26` and got the same result.  So I don't think that my ~/.emacs.d config or packages are interfering.

I'm sorry to be putting you to so much trouble for something that is clearly not your fault.  I owe you one, so let me know if there's some menial task I can do for Elfeed.  :)  Thanks.

**Comment by alphapapa** [comment]
BTW, I just ran the test again under a different user account on my system (i.e. `cp -a ~/src/emacs/elfeed /tmp/elfeed; su - test; cd /tmp/elfeed; ./testingissue279.sh`) and got the same result.  :(

**Comment by alphapapa** [comment]
By the way, I just noticed something else strange in my Emacs.  I recently discovered that `paradox` has a command to show commits for a package, and it highlights ones made since the version you currently have installed.  A few weeks ago it seemed to work fine.  But now every commit shows the date 1999-12-31, which is the result of one of the test commands you had me run.  Seems likely to be connected to this problem, and indicates a problem in Emacs as a whole rather than in Elfeed.  :(

**Comment by skeeto** [comment]
This does seem like Emacs itself is broken. Your test script looks 
correct, though it's still puzzling that the ERT tests pass. Maybe the 
date issue only occurs when you're using the GUI? There's something 
different going on between batch mode (where the tests pass) and Emacs 
running normally.

If it happens in different Emacs versions and even when you rebuild it, 
maybe your OS is screwed up, like libc is damaged or something else 
related to time.

**Comment by alphapapa** [comment]
I don't think it's caused by the GUI, because it also happens when I run the test file in terminal mode (e.g. `emacs -nw`).

And I don't think it's related to Emacs in batch-mode, because I just tried this in the test script, replacing the last line with:
```sh
$EMACS -L . -l elfeed.elc -f elfeed --batch --eval '(progn (elfeed-add-feed "https://nullprogram.com/feed/") (elfeed-update) (sit-for 5) (message "%s" (buffer-string)))'
```
And the output was:
```
Ran 34 tests, 34 results as expected (2018-06-14 12:41:31-0500)

2018-06-14 Two Chaotic Moti null program (unread)
2018-06-14 Emacs Lisp Lambd null program (unread)
2018-06-14 A Crude Personal null program (unread)
2018-06-14 Blast from the P null program (unread)
2018-06-14 When the Compile null program (unread)
2018-06-14 When FFI Functio null program (unread)
2018-06-14 Emacs 26 Brings  null program (unread)
2018-06-14 Minimalist C Lib null program (unread)
End of entries.
```
This sure is bizarre.  Not having any other issues on my system.

**Comment by alphapapa** [comment]
Found the issue, something wrong with `load-path`, standby...

**Comment by alphapapa** [comment]
Wow, well this has been a ride, and I still don't have any idea how it happened, but I got it fixed.

The problem was that a very old version of `timezone.el` was being loaded into Emacs, and it was failing to parse some date formats (and other functions weren't checking the results along the way, so no errors were raised, and things happened like `nil` values for `month` in one function causing the month to always be December).

That old version of `timezone.el` came from an Ubuntu package called `apel`, the version of which was from 2012.

Now that shouldn't be a problem, because `timezone.el` is also found in:
```
/usr/share/emacs/25.2/lisp/timezone.el.gz
/usr/share/emacs/25.2/lisp/timezone.elc
/usr/share/emacs/26.1/lisp/timezone.el.gz
/usr/share/emacs/26.1/lisp/timezone.elc
```
But for some reason, in `load-path`, `"/usr/share/emacs/site-lisp/apel/attic"` came before `"/usr/share/emacs/25.2/lisp"`.

I would hope that some code, somewhere, would choose the newer version (I even have `load-prefer-newer` set to `t`), but apparently not.

So I removed the `apel` package, and now everything works fine.

But `apel` was not recently installed on my system; I can't even find it in any apt or dpkg logs.  So why did its directory suddenly start getting loaded before the others?

Well, on May 31 I installed emacs26, which I built myself using a source package from this PPA: https://launchpad.net/~kelleyk/+archive/ubuntu/emacs  I had to build it myself because his build config wouldn't work on Trusty:

> The `emacs26` packages have `mailutils` and `systemd` support (the two build-time options that are new in `emacs26`) enabled. The `emacs26` packages for 14.04 have failed to build because not all of the dependencies that are required to enable these options are available.

I don't need or use either of those, so I removed them from the build config, and the package built and installed (and works) fine.

And guess what file is included in that package: `/usr/share/emacs/site-lisp/subdirs.el`, which contains only:
```el
(if (fboundp 'normal-top-level-add-subdirs-to-load-path)
    (normal-top-level-add-subdirs-to-load-path))
```
There are other `subdirs.el` on my system, but they are all in version-specific directories:
```
/usr/share/emacs/24.5/lisp/subdirs.el
/usr/share/emacs/25.2/lisp/subdirs.el
/usr/share/emacs/26.1/lisp/subdirs.el
/usr/share/emacs/26.1/site-lisp/subdirs.el
/usr/share/emacs/site-lisp/subdirs.el
/usr/share/emacs24/site-lisp/subdirs.el
/usr/share/emacs25/site-lisp/subdirs.el
```
And the `apel` package installs to `/usr/share/emacs/site-lisp/apel`.

So the `subdirs.el` file in that emacs26 package was causing those old `apel` directories to show up in `load-path`, causing the old version of `timezone.el` to get loaded.  To be sure, I reinstalled the old `apel` package and then removed `/usr/share/emacs/site-lisp/subdirs.el`, and that prevented `apel`'s `timezone.el` from overriding the correct, version-specific one from `emacs25-common` and `emacs26-common`.

So this had nothing whatsoever to do with Elfeed, it was just where I noticed the problem happening.  I think it didn't happen in all Emacs date-related code, because the old `timezone.el` `timezone-parse-date` function worked fine for some date formats, but newer ones support more formats, including one of the ones that Elfeed's code uses.

By the way, I finally traced the problem by `edebug-defun`ning a chain of date-related functions, and when I got to `timezone-parse-date`, I looked at the mode-line and saw that it was in an `apel` directory, which seemed strange to me.  Then I ran `locate timezone.el` and found the version-specific ones, and then I used this code to find copies in my `load-path` that were being loaded:
```el
(cl-loop for dir in load-path
         when (f-exists? dir)
         when (--any (string-prefix-p "timezone.el" it)
                     (mapcar #'f-filename (f-files dir)))
         collect dir)  ;; => ("/usr/share/emacs/site-lisp/apel/attic" "/usr/share/emacs/25.2/lisp")
```
And as you can see, the `apel` one is found first (assuming that this emulates the way Emacs searches for them).

So, Chris, I am very sorry for wasting your time on this.  I could have tracked it down on my own if I had done earlier what I did today.  Thank you very much for your patience and help.

By the way, @kelleyk, if you get this: This is not to blame you at all (I did modify and build the packages myself, after all), but this may be something you should be aware of.  Maybe the packaging needs to be adjusted for Trusty, because the Emacs 25 packages I built installed `subdirs.el` to:
```
/usr/share/emacs25/site-lisp/subdirs.el
/usr/share/emacs/25.2/lisp/subdirs.el
```
rather than `/usr/share/emacs/site-lisp/subdirs.el`, so they didn't load  `apel`'s files.  But thank you anyway, Kevin, because your packaging did save me from having to package Emacs 26 myself.  :)
