### ISSUE TITLE
Update failures

### ISSUE THREAD

**Issue by jsynacek** [skeeto/elfeed#28]
Updating some of my feeds fails with:

Elfeed update failed for http://www.drdobbs.com/rss/all: (:error (error connection-failed "failed with code 101\n" :host "www.drdobbs.com" :service 80))
Elfeed update failed for http://www.drdobbs.com/rss/all: (:error (error connection-failed "deleted\n" :host "www.drdobbs.com" :service 80) :error (error connection-failed "failed with code 101\n" :host "www.drdobbs.com" :service 80))
Elfeed update failed for http://wz2100.net/news/feeds/atom/: (:error (error connection-failed "failed with code 101\n" :host "wz2100.net" :service 80))
Elfeed update failed for http://wz2100.net/news/feeds/atom/: (:error (error connection-failed "deleted\n" :host "wz2100.net" :service 80) :error (error connection-failed "failed with code 101\n" :host "wz2100.net" :service 80))
Elfeed update failed for http://feeds.feedburner.com/Phoronix: (:error (error connection-failed "failed with code 101\n" :host "feeds.feedburner.com" :service 80))
Elfeed update failed for http://feeds.feedburner.com/Phoronix: (:error (error connection-failed "deleted\n" :host "feeds.feedburner.com" :service 80) :error (error connection-failed "failed with code 101\n" :host "feeds.feedburner.com" :service 80))

They all work well when viewed from Firefox or when fetched via Thunderbird.

**Comment by mrvdb** [comment]
I have an issu that looks similar to this. When ipv6 is enabled, my emacs even crashes reliably on fetching new feed entries.
If I disable ipv6, everything is fine. 
(emacs-version) GNU Emacs 24.5.1 (parabola linux)

**Comment by skeeto** [comment]
This should mostly be fixed by the switch to the curl backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/)
