### ISSUE TITLE
Exception (wrong-type-argument number-or-marker-p  language)

### ISSUE THREAD

**Issue by sarg** [skeeto/elfeed#285]
I get this error in `*elfeed-log*`
```[2018-07-01 07:51:10] [error]: https://blog.benjojo.co.uk/rss.xml: (wrong-type-argument number-or-marker-p  language)```

Seems that this is the faulty entry:
```xml
     <item>
      <title>Lessons from APL, a &#34;lost&#34; language&#xD;</title>
      <link>https://blog.benjojo.co.uk/post/2014-05-26-APL-the-lost-language.md</link>
      <description>Lessons from APL, a &#34;lost&#34; language&#xD;&#xA;===&#xD;&#xA;&#xD;&#xA;A few weeks back the forum that I go on often held a obfuscation challenge, and people joked around about submitting a entry that was coded in APL.&#xD;&#xA;&#xD;&#xA;APL (A Programming Language) is a programming language that w</description>
      <author>Ben Cox</author>
      <pubDate>Mon, 26 May 2014 19:03:53 +0000</pubDate>
    </item>
```

**Comment by skeeto** [comment]
I'm unable to reproduce this issue for that feed. The sample you 
provided looks fine, and the feed itself also seems to be fine. The 
encoding of the carriage return and line feed (&#xD;&#xA;) is strange, 
but it's perfectly legal and shouldn't cause any issues.

What version of Elfeed, Emacs, and operating system are you using?

**Comment by sarg** [comment]
debian testing, emacs-snapshot (27.0.50), elfeed 3.0.0
the issue is reproducible every time I refresh the feed. Maybe something is corrupted in db?

**Comment by sarg** [comment]
Oh, I found the reason for that. Some time ago I have somehow got elfeed db corrupted. All unicode symbols were written escaped (like "\307\204\304\145..."). I have repaired db using simple python script and got wrong with the quotes. Sorry for bothering you. Elfeed rocks, btw!
