### ISSUE TITLE
Failed to load images in entries through proxy

### ISSUE THREAD

**Issue by whatacold** [skeeto/elfeed#289]
Hi,

I need to fetch some feeds throught proxy, with `elfeed-curl-extra-arguments` being set, it works.

But it can't load the images in the entries when I read them,
I have tried to set env like below, but it can't help:

    (let ((proxy "socks5h://localhost:1080"))
      (setenv "http_proxy" proxy)
      (setenv "https_proxy" proxy)
      (setenv "HTTPS_PROXY" proxy))

How can I properly set it up? Thanks.

**Comment by whatacold** [comment]
And below code doesn't help neither:

    (setq url-gateway-method 'socks)
    (setq socks-server '("Default server" "127.0.0.1" 1080 5))

**Comment by whatacold** [comment]
Is there any way for manually loading the image, like `i` in `w3m`?

I found no such binding with `C-h m`.

**Comment by skeeto** [comment]
Elfeed uses curl (when available) to download feeds, but when you view 
entries with elfeed-show-mode it uses eww to render it. Therefore 
external content is fetched by Emacs itself via the usual means. I 
*think* the configuration you tried with url-gateway-method should do 
the trick, or at least something with url-proxy-services.

However, it looks like prior to Emacs 26 there's an Emacs bug that 
prevents eww from using this configuration:

https://emacs.stackexchange.com/questions/19161/eww-cannot-access-https-sites-via-proxy

That may be the source of your problem.

**Comment by whatacold** [comment]
I fix this problem by using privoxy to "translate" socks to http proxy,
then set `url-proxy-services` for `elfeed-show-mode` buffer:

    (add-hook 'elfeed-show-mode-hook
              #'(lambda ()
                  (setq-local url-proxy-services '(("http" . "127.0.0.1:8118")
                                                   ("https" . "127.0.0.1:8118")))))

Thanks.

P.S. My Emacs is 26.1 already.
