### ISSUE TITLE
How disable incremental search in Elfeed?

### ISSUE THREAD

**Issue by fturco** [skeeto/elfeed#299]
Is there a way to disable incremental search in Elfeed? I would prefer Elfeed to update my article list only after having fully typed my search keywords and pressed enter. This is due to the fact that Elfeed sometimes slows down for a few seconds while typing my search keywords.

I'm using:
- Elfeed 20181127.1943
- Emacs 26.1
- Gentoo Linux

**Comment by skeeto** [comment]
Instead of "s" (elfeed-search-live-filter), use capital "S" 
(elfeed-search-set-filter). If you want this to be the default, then 
change the keybinding for "s" to use the latter function.

**Comment by fturco** [comment]
`elfeed-search-set-filter` is exactly what I need. Thank you!
