### ISSUE TITLE
Unwanted interrupts

### ISSUE THREAD

**Issue by sabof** [skeeto/elfeed#30]
If I press `C-g` for any reason while elfeed is updating, I will get a `(:error (error "Transfer interrupted!"))`. The solution is to wrap the callbacks, or at least some portions with

``` lisp
(let ((inhibit-quit t)) 
  ;; ...
)
```

Obviously the code inside this section must never hang.

**Comment by skeeto** [comment]
This should mostly be fixed by the switch to the curl backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/)
