### ISSUE TITLE
Date ranges?

### ISSUE THREAD

**Issue by rksm** [skeeto/elfeed#305]
Thanks for providing my daily news interface!

Question 1: Is there any support for date ranges? I would have expected that something like `-@1-day-ago @2-days-ago` would give me all of the posts matching inbetween those times?

Question 2: Is there any support to specify absolute dates / times? `@2019-02-19`?

**Comment by skeeto** [comment]
Currently there is no support for date ranges in the search filter, 
including specific or absolute datetimes. I don't object to Elfeed 
getting such a range feature so long as it has well-designed syntax / 
notation.

**Comment by rksm** [comment]
OK, I don't know how much time I'll have for this, it could be a few weeks but I would be generally be interested in drafting a PR.

So for specifying an "absolute ago" how about something that is ISO 8601 inspired (`(format-time-string "%F")` and `(format-time-string "%FT%H:%M:%S")`) together with a descriptive keyword, something like `@since-2019-02-19`, `@since-2019-02-19T13:30:00`. 

For ranges, how about reusing "--" from org ranges for something like `@2-days-ago--4-days-ago`. Semantically, @start--end. Absolute and relative date/times could be mixed like `@2-days-ago--2019-02-12` but absolute dates would loose their `since-` key.

**Comment by skeeto** [comment]
I like the idea of reusing a concept from Org. Plus that should be easy 
to parse: split on "--" and pass each side to elfeed-float-time. The 
filter parser would need to be extended to have a beginning and ending 
time range, along with the parser interpreter and compiler.

**Comment by rksm** [comment]
OK, will take a stab at it.
