### ISSUE TITLE
Show/hide/scale images

### ISSUE THREAD

**Issue by Fuco1** [skeeto/elfeed#31]
Hi.

My main notebook is a 11" netbook which I love and carry everywhere. The issue with elfeed is that the (bigger) images in the posts take up all the screen and the scrolling gets very confusing.  It would be awesome if I could toggle image display or scale them to say 20% to have an overview.

I looked at the code a bit but didn't figure out how you actually render the feeds (though I only looked very briefly, I'm quite busy at the moment :/)

If you see an easy way to implement this, I would be very thankful, otherwise I can take a stab at it and send some patch, but no sooner than next month.

Thanks for the amazing package!

**Comment by skeeto** [comment]
Closing since this issue is over a year old and Elfeed is working correctly in this case.

**Comment by vikasrawal** [comment]
I seem to be facing this behaviour:  https://www.reddit.com/r/emacs/comments/esa3x5/image_scaling_in_elfeed_entry_window/

It does not look like image scaling works as expected. Has this been attended to?
