### ISSUE TITLE
How can I mark entries with certain tag as read if older than N days?

### ISSUE THREAD

**Issue by semente** [skeeto/elfeed#316]
Preferable if I could use `elfeed-new-entry-hook`. Thank you.

**Comment by skeeto** [comment]
Here's how I do it:

https://github.com/skeeto/.emacs.d/blob/514d7a29fec619f0c70c999be00c84867976dbed/etc/feed-setup.el#L93

(add-hook 'elfeed-new-entry-hook
          (elfeed-make-tagger :before "7 days ago"
                              :remove 'unread))

**Comment by semente** [comment]
Hey, thanks! But I'm looking for mark entries with a certain **tag** and age as read. For instance, mark all entries tagged as "dailynews" and  that are  2 days old as read.

Any idea? :)

**Comment by skeeto** [comment]
You can still use the new entry hook. The "autotags" are already applied 
before the hook is called. In your hook function check the entry's tags 
(elfeed-entry-tags) and remove the "unread" tag if the condition is met.

**Comment by semente** [comment]
Awesome! I will do that. Thank you

**Comment by semente** [comment]
Hey @skeeto, I tried to achieve this by customizing yours `elfeed-make-tagger`. I end up with the following function:

```
(cl-defun semente-elfeed-make-tagger
        (&key feed-title feed-url entry-title entry-link entry-tag after before
              add remove callback)
      (let ((after-time  (and after  (elfeed-time-duration after)))
            (before-time (and before (elfeed-time-duration before))))
        (when (and add (symbolp add)) (setf add (list add)))
        (when (and remove (symbolp remove)) (setf remove (list remove)))
        (lambda (entry)
          (let ((feed (elfeed-entry-feed entry))
                (date (elfeed-entry-date entry))
                (case-fold-search t))
            (cl-flet ((match (r s)
                             (or (null r)
                                 (if (listp r)
                                     (not (string-match-p (cl-second r) s))
                                   (string-match-p r s)))))
              (when (and
                     (match feed-title  (elfeed-feed-title  feed))
                     (match feed-url    (elfeed-feed-url    feed))
                     (match entry-title (elfeed-entry-title entry))
                     (match entry-link  (elfeed-entry-link  entry))
                     (match entry-tag   (elfeed-entry-tags  entry))
                     (or (not after-time)  (> date (- (float-time) after-time)))
                     (or (not before-time) (< date (- (float-time) before-time))))
                (when add
                  (apply #'elfeed-tag entry add))
                (when remove
                  (apply #'elfeed-untag entry remove))
                (when callback
                  (funcall callback entry))
                entry))))))
```

Basically it changes two lines of the original function: the header and adds a new line `                     (match entry-tag   (elfeed-entry-tags  entry))`.

The hook looks like the following:

```
    ;; mark entries that are tagged as daily and that are older than 2 days as read
    (add-hook 'elfeed-new-entry-hook
              (semente-elfeed-make-tagger :entry-tag "daily" :before "2 days ago" :remove 'unread))
```

But unfortunately something bad is happening. I did delete the elfeed database in order to test it and when I call `update-feed` for the first time I still see the message "Database empty. Use elfeed-add-feed, [...]". It indeed fetch some entries and list them below this message, but seems very incomplete compared when I don't use this hook against an empty database. Anyway, without this hook the line "Database empty" disappear as soon I call `elfeed-update` and become "Updated [...]" after finished but using my hook it is always "Database empty".

No error message is shown in `*Messages*` buffer. I'm not sure exactly what `elfeed-entry-tags` returns neither if the `match` function can work with this data. Could you help me with this? Thank you.

**Comment by semente** [comment]
Well, for those interested, this can do the job:

```
(defun semente-elfeed-mark-old-daily-tagged-entries-as-read (entry)
      (let ((date (elfeed-entry-date entry))
            (before (elfeed-time-duration "1 day ago")))
        (when (and
               (member 'daily (elfeed-entry-tags entry))
               (or (< date (- (float-time) before))))
          (apply #'elfeed-untag entry (list 'unread)))))

(add-hook 'elfeed-new-entry-hook 'semente-elfeed-mark-old-daily-tagged-entries-as-read)
```

No idea why the function in the previous comment didn't work.
