### ISSUE TITLE
Switch article font to fixed width font

### ISSUE THREAD

**Issue by fshapps** [skeeto/elfeed#318]
Hi - by default elfeed uses a variable width font for the articles (see attached). How do I change to fixed width? I read through #190 but am not familiar enough with elisp to modify appropriately. Thanks.
<img width="1055" alt="Screen Shot 2019-05-11 at 9 50 48 AM" src="https://user-images.githubusercontent.com/4127972/57570690-c8c21600-73d2-11e9-9052-acbbc24397cb.png">

**Comment by skeeto** [comment]
The situation has changed a bit in Emacs itself since that other issue 
was opened. If you're using Emacs 25.1 or later, set shr-use-fonts to 
nil to switch to a fixed-width font. The styles in elfeed-show are 
chosen by shr, not Elfeed, so it's mostly about configuring shr to get 
what you want.

**Comment by fshapps** [comment]
That worked perfectly. Thank you!
