### ISSUE TITLE
Error on elfeed-curl--call-callback while fetching entries

### ISSUE THREAD

**Issue by semente** [skeeto/elfeed#319]
I'm using an Emacs snapshot from git master on a Debian buster/testing system. Elfeed is the latest from melpa (20190502.1214). I always get the following error when I run `elfeed-update`:

```
Error running timer ‘elfeed-curl--call-callback’: (search-failed "HTTP/[.0-9]+ +\\([0-9]+\\)") [14 times]
```

It seems it is preventing to get all entries of some feeds. Any idea? Thanks

**Comment by semente** [comment]
Oops, my bad. I had an custom `user_agent` in the `.curlrc` on this machine

**Comment by skeeto** [comment]
Hmmm, perhaps by default Elfeed should use curl's --disable option to 
disable use of the ".curlrc" file.

**Comment by semente** [comment]
Yea, I think it is a good idea the default `curl` command have the `--disable` argument and the user  could customized it if ever needed.
