### ISSUE TITLE
Elfeed index large file query blocks shutdown

### ISSUE THREAD

**Issue by hughwilliams94** [skeeto/elfeed#321]
I run emacs as a daemon via systemd. When I try to stop the emacs.service or shutdown my PC emacs gives a prompt stating that `.elfeed/index is a large file` this prompt requires a repsonse and therefore the shutdown hangs until emacs is terminated. How can I avoid this prompt appearing?

**Comment by skeeto** [comment]
Maybe try setting large-file-warning-threshold to a larger value, or 
nil. As of Elfeed 1.2.0 (October 2015) you should be seeing this warning 
anyway since Elfeed disables it.

If you're using Spacemacs you might need to configure 
dotspacemacs-large-file-size since it adds an additional warning.

**Comment by hughwilliams94** [comment]
I have set the large-file-size variable to nil and the issue has been resolved. Cheers!
