### ISSUE TITLE
elfeed-search-mode keymap suggestions

### ISSUE THREAD

**Issue by cowile** [skeeto/elfeed#323]
Recently started using elfeed as a replacement for newsboat. It works great, and now I don't need to leave emacs and can display pictures inline.

But before getting comfortable, I did need to write additional keybindings, and I think some of them would be useful for everyone.

Bind "<" and ">" to beginning-of-buffer and end-of-buffer because I often want to start at one end of the list and the normal "M-<", "M->" keys weren't convenient enough.

Bind "h" to describe-mode consistency with other emacs features like dired and buffer menu. Helped me learn keys much faster.

Define a function "elfeed-clear-filter" and bound it to "c" to reset my filter to the default because I noticed how often I went back and forth between my default filter and one additional tag.

Would you like a pull request for these?

**Comment by skeeto** [comment]
Sure, I'd accept these new keybindings. They follow conventions and 
shouldn't break anything.
