### ISSUE TITLE
Sort by oldest first

### ISSUE THREAD

**Issue by echosa** [skeeto/elfeed#327]
Is it possible to change the sort order to show oldest first rather than newest first? I don't see a way, or at least haven't figured out how to do so.

**Comment by skeeto** [comment]
Set elfeed-sort-order to ascending:

(setf elfeed-sort-order 'ascending)

The docstring for that variable mentions a caveat for live filters.

**Comment by echosa** [comment]
Ah, thank you! I've customized that variable now.
