### ISSUE TITLE
Search or filter by feed name/title

### ISSUE THREAD

**Issue by echosa** [skeeto/elfeed#328]
I have a tag for all my YouTube RSS feeds. That lets me show just YouTube entries with `+youtube`. However, inside that filter, I'd like to then be able to search/filter just the entries for a particular channel. However, I don't see a way to search or filter based on the feed name. When I type in plain search/filter text, it only matches on the article titles, not the feed names. Is there a way to do this?

**Comment by skeeto** [comment]
Use the "=" prefix to match feed titles and URLs. Example:

@1-month-ago +youtube =PewDiePie

https://github.com/skeeto/elfeed#filter-syntax

**Comment by echosa** [comment]
Oh, perfect. I missed that. Thanks!
