### ISSUE TITLE
If article has multiple authors, only the first one is saved

### ISSUE THREAD

**Issue by herrsimon** [skeeto/elfeed#329]
If an (atom) feed entry has multiple <author> tags, elfeed only saves the first as author. Would it be possible to save all of them, by 

a) concatenating all authors into a single string (authors John Doe and Foo Bar would become "John Doe, Foo Bar") and then saving it as the "author" meta-entry.

b) saving them as a list in the database (as is done for the categories), maybe as an "authors" meta-entry and optionally providing a convenience function which concatenates them? An example of such a convenience function would be 

```lisp
(defun concatenate-strings (sequence separator)
   (substring (reduce #'(lambda (current next)
                          (if (stringp next)
                              (concatenate 'string current separator next)
                            current ))
                      sequence
                      :initial-value "") 2)
```

so that

```lisp
(concatenate-strings (elfeed-meta entry :authors) ", ")
```
would yield the desired string with all authors.

Background: I'm using elfeed to monitor scientific articles on arxiv.org. If an article has multiple authors, each has its own <author> tag in the corresponding feed item. See for example this query:

http://export.arxiv.org/api/query?search_query=cat:math.FA

I have written my own elfeed-search-print-entry function to also include the authors in the search view but currently only the first author is shown, which is very inconvenient.

**Comment by skeeto** [comment]
Yup, I've neglected to parse multiple authors. I just pushed 99855cf 
which parses all authors for both Atom and RSS. RSS doesn't support 
multiple authors, but the Dublin Core extension does. Again, Atom has 
the best design, so Elfeed's structure is modeled after it.

The meta slot has been renamed to :authors (plural) to reflect the 
change. The feed slot can't reasonably be renamed, so it remains 
"author" despite being a list of authors (usually a list of zero or 
one).

The new format is a list of plists (:name, :uri, :email) with each 
component separated, so you can use each part as you like.

**Comment by herrsimon** [comment]
Thanks a lot, works like a charm! One more thing: Could you also adjust elfeed-show so that all authors are shown instead of just the first one?

If somebody stumbles across this later: here is my function which generates the above mentioned string "author1, author2" to include in a custom notmuch-search view:

```lisp
(defun sc/generate-authors-string (authors-list)
  "generate authors string from elfeed-meta-entry :authors"
  (let (authors)  
    (substring
     (dolist (author authors-list authors)
       (setq authors (concat authors ", " (plist-get author :name))))
     2)))
```

**Comment by skeeto** [comment]
I settled on listing the "Author:" header multiple times since I think 
that looks nicest, but I suppose it's not very RFC-like.

**Comment by herrsimon** [comment]
perfect, thanks!
