### ISSUE TITLE
Elfeed marks previously read items as unread

### ISSUE THREAD

**Issue by SidharthArya** [skeeto/elfeed#331]
i use elfeed to read my daily news, but sometimes a news item that has already been read is again either marked as read or refetched into the cache, I am not sure. But for me the intended behavior would be to not see the already read items again.
Can I achieve this somehow?

**Comment by oystersauce8** [comment]
i've noticed this too.
i figured the problem was with the news provider, but now im thinking maybe
its elfeed.

**Comment by skeeto** [comment]
That isn't the intended behavior. There could be a couple of causes:

1. If Emacs doesn't shut down cleanly then you will lose recent database 
changes. That includes tag changes and recently-fetched items. This can 
easily be the case if you use the Emacs server and the server instance 
never gets a chance to exit gracefully (killed on logout, etc.). You can 
force a database save at any time with elfeed-search-quit-window (q), 
killing the listing buffer, elfeed-db-unload, or gracefully exiting 
Emacs.

2. Some feeds are just broken or mismanaged such that they occasionally 
republish the same item with a different ID, signaling to feed readers 
that the old item is actually a new, unique item. If you broaden the 
search filter and find a duplicate listing for an item that has 
reappeared as unread, then this is the case. If it's possible for you to 
share the URL of one of these misbehaving feeds, I'd like to see it.

**Comment by SidharthArya** [comment]
@skeeto I understand what you mean. I am closing this issue for now.

**Comment by tleydxdy** [comment]
I think it would be great if read/unread info are flushed more frequently, currently I often loose days of feed/read data because I never close emacs unless I reboot.
