### ISSUE TITLE
elfeed-update changes current-buffer

### ISSUE THREAD

**Issue by ReichKV** [skeeto/elfeed#335]
Hi,

Every time I start "elfeed-update", my current-buffer is switched. So my step are following:
1.The current buffer is *scratch*
2. M-x elfeed-update
3. The current buffer is *Message*

Is it possible to suppress this behavior?

**Comment by seblemaguer** [comment]
I don't have this problem on my side, are you sure you didn't configured a hook by mistake (for example: elfeed-update-init-hooks ?)

**Comment by ReichKV** [comment]
Yeah, the problem on my side. But I cannot figure out where.  Do you have any ideas?

**Comment by ReichKV** [comment]
Ok, i have problem with this code in my config:

(setq protected-buffer-list '("*scratch*" "*EMMS*"))
(defadvice kill-buffer (around kill-buffer-around-advice activate)
  (if (member (buffer-name (current-buffer)) protected-buffer-list)
      (bury-buffer)
    ad-do-it))
