### ISSUE TITLE
Sometime ago elfeed stopped updating

### ISSUE THREAD

**Issue by Wojtek242** [skeeto/elfeed#341]
When I run elfeed-update my feed does not update. I tried following up the other issues that described the same problem, but they don't seem to apply to me.

The only way I managed to get my feed to update by closing emacs, removing the `.elfeed` directory and reopening emacs to run elfeed again. But then it failed to update the next day until I repeated these steps. This suggests that everything is fine with curl and so on, but something went wrong with how the index is updated.

Any suggestions on what I could try?

**Comment by skeeto** [comment]
Just to make sure we're on the same page: You have to manually initiate 
updates with M-x elfeed-search-fetch (G). It never fetches feeds on its 
own, which is a little bit unconventional.

Do you see anything in *elfeed-log*? Ideally you'll see an "info" 
message about the update and no errors. Similarly, are there any Elfeed 
messages in *Messages*?

Are you sure elfeed-feeds is populated with URLs, that it's not nil?

Can you update an individual feed with M-x elfeed-update-feed?

**Comment by Wojtek242** [comment]
Actually, never mind - the issue appears to have sorted itself out. I will re-open if it reoccurs.

To clarify what I meant:
1. I would have elfeed open
2. Running elfeed-update would not pull in any new entries
3. No suspicious entries in *elfeed-log* or *Messages*

Deleting `.elfeed` while Emacs was closed seems to have resolved it (even though it didn't appear so at first).
