### ISSUE TITLE
Date parse edge cases

### ISSUE THREAD

**Issue by merrickluo** [skeeto/elfeed#345]
I have some RSS feeds that date can not be correctly parsed

- Atom feeds that have the date in `pubDate` tag
like this http://blog.icehoney.me/feed
- RSS 2.0 feeds that have the date in format `2019/11/15 10:00:00`
like this https://blog.csdn.net/pennyliang/rss/list

The first case can be fixed by adding a pubDate query `(xml-query* (pubDate *) entry)` in `elfeed-entries-from-atom` function, and I'm using an advice to fix the second one, I think it will be great if you can include these patch in elfeed as well.

**Comment by skeeto** [comment]
I understand the annoyance with such malformed feeds, but I'm only 
willing to go so far to accommodate them. Despite their issues, both 
feeds *do* still work in Elfeed, just with the fetch date as the entry 
date. Elfeed should be locking in and remembering that initial fetch 
date and not bumping it forward on later fetches. If you find that it 
doesn't, that's something I would like to fix. This is the general 
solution for feeds with missing or invalid date formats.

Sometimes it helps convince feed publishers to fix their broken feed if 
you can show that their feed doesn't validate. Here are the links 
showing the W3 validator rejecting each of those feeds:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.csdn.net%2Fpennyliang%2Frss%2Flist
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.icehoney.me%2Ffeed

**Comment by merrickluo** [comment]
Yeah, I know it's not a big issue, the only reason I notice this is I'm having a hard time sync elfeed DB across devices, it gets re-fetching a lot. I'm reading the old issues about sync, I hope I can get it to work, so I guess I'm closing this?
