### ISSUE TITLE
Excluding feeds ?

### ISSUE THREAD

**Issue by aagon** [skeeto/elfeed#347]
Hello Mr. Wellons,

First of all, thank you for this wonderful package. I (almost) do not need to go open youtube.com in a web browser anymore.

Certain feeds tend to have a lot more output than others, thus cluttering the elfeed-search buffer. There is a way to display only entries coming from certain feeds ('='), but none to display entries **not** coming from certain feeds.

One solution would be to have separate tags for each feed, and then use -. But I found the implementation of the "exclude-feed" filter quite easy.

I will open a PR immediately, and comment more extensively on my changes

Thank you again,

Aymeric Agon-Rambosson

**Comment by skeeto** [comment]
Fixed by #348.
