### ISSUE TITLE
How to investigate feed fetched content log?

### ISSUE THREAD

**Issue by stardiviner** [skeeto/elfeed#355]
```
Title: 热烈祝贺深圳希玛眼科医院获「最佳组织管理」荣誉称号
Date: Thu, 16 Jan 2020 08:00:00 CST
Feed: 谢乾坤 | Kingname
Tags: Blog, read
Link: http://yyh.dxy.cn/article/674704
Enclosure: https://img1.dxycdn.com/2020/0116/914/3391204847952406751-10.jpg

1 月 11 日，在深圳人才园以「破局·赋能·创新」为主题的 2020 年人才引进与组织发展高峰论坛暨 2019 年度深圳市中小企业最佳雇主评选颁奖典礼隆重举行。各
领域专家与企业高层齐聚一堂，围绕人才生态环境建设、招才引智等主题，共话人才融合发展创新大计。经过层层严格评选、考核、调研，深圳希玛眼科医院在深圳
市中小企业最佳雇主评选活动中荣膺「最佳组织管理」称号！
```

But the feed RSS of Kingname is "http://www.kingname.info/atom.xml".

I opened that RSS URL in web browser, it does not contains upper rss articles.
This is very weird, I suspend someplace network insert those Ads to my traffic
packates. How can I find out?

I used to saw this problem on feed "http://linux.cn/rss.xml" too.

Does elfeed have a way to log all fetch RSS content, so I can search through.

**Comment by skeeto** [comment]
When I fetch this feed, I do not see any article newer than January 1, 
2020, so perhaps someone in the middle is injecting extra content. I can 
also access this feed via HTTPS, so perhaps you could try that to avoid 
any MITM shenanigans.

Elfeed does not log to such a level of detail as to track individual 
entries. If I need to debug a particular feed, I'll download a copy and 
manually parse it with elfeed-xml-parse-region and elfeed-entries-from-X 
(where X is the appropriate feed type). You'd need a decent handle on 
Emacs Lisp to work with these functions, though.

**Comment by stardiviner** [comment]
I see, thanks for investigating. I will try to switch to HTTPs for security.
