### ISSUE TITLE
How to set a default font while reading news?

### ISSUE THREAD

**Issue by ClemFandango2** [skeeto/elfeed#369]
When I pick a post, it's rendered with too big font... how to fall back to a default font I have?
In eww I switch from "proportional font" to default one using "F".

BTW, when I loaded eww, press "F" and loaded elfeed after, the font is standard, not "variable-pitch".

**Comment by skeeto** [comment]
I think you just need to customize the variable-pitch face.

**Comment by ClemFandango2** [comment]
How to do it? Sorry, Emacs noob here.

**Comment by ClemFandango2** [comment]
Ah, found!
And thanks for your work on elfeed!
