### ISSUE TITLE
support xml:base attribute in atom feeds

### ISSUE THREAD

**Issue by brabalan** [skeeto/elfeed#37]
As illustrated by the feed from Xah Lee (http://ergoemacs.org/emacs/blog.xml), some feeds use the xml:base attribute in the main <feed> tag to provide the url to which other entries may be relative. It would be great if elfeed could support it.

**Comment by skeeto** [comment]
Closing since this was fixed in db17c4db4ff81c5a7a2bc9950884a69d26ca3a0a.

**Comment by xahlee** [comment]
hi skeeto, seems this issue is back?
