### ISSUE TITLE
[Question] Possibility to use different faces fro elements with multiple tags ?

### ISSUE THREAD

**Issue by dinkonin** [skeeto/elfeed#372]
Hello currently I customize  `elfeed-search-face-alist` like this 
```elisp
(push '(software my-software-elfeed-entry)
      elfeed-search-face-alist)
```
is it possibile to have a different face for items tagged with an additional tag i.e. `software,emacs` <> `software,vim` or even `unread,software,emacs`

**Comment by skeeto** [comment]
Sorry, this is not possible at the moment. It only considers individual 
tags when choosing faces.

**Comment by dinkonin** [comment]
I've written an advice to `elfeed-search--faces` which works for me 
```elisp
(defun elfeed-search--faces-advice (tags)
  "Return all the faces that apply to an entry with TAGS."
  (nconc (cl-loop for (tag . faces) in elfeed-search-face-alist
                  when (if (listp tag) (cl-subsetp tag tags) (cl-subsetp (list tag) tags))
                  append faces)
         (list 'elfeed-search-title-face)))
```

That way i can do both  `(push '(software important-elfeed-entry)...` and  `(push '((software,emacs) important-elfeed-entry)`

Am I missing something , should I make a PR (I was scared to do it because my elisp skills are severely lacking)
