### ISSUE TITLE
Starting elfeed on Emacs 27.1 Produces Wrong type argument: wholenump, -1

### ISSUE THREAD

**Issue by jandrusk** [skeeto/elfeed#406]
Starting elfeed on Emacs 27.1 Produces Wrong type argument: wholenump, -1.

**Comment by jandrusk** [comment]
Here's the debug output from trying to start elfeed. Seems to have an issue with my elfeed.org file, though I haven't changed anything with it in some time. 

https://pastebin.com/bmMAuX8J

**Comment by skeeto** [comment]
Perhaps you've set org-indent-indentation-per-level 0? The crash is 
caused by something deep in Org, and looking at the Org source code 
that's the only thing that makes sense for this backtrace.

**Comment by jandrusk** [comment]
> Perhaps you've set org-indent-indentation-per-level 0? The crash is caused by something deep in Org, and looking at the Org source code that's the only thing that makes sense for this backtrace.

Thanks, that was it. If I either comment it out or change it to a non-zero value the problem goes away. I'll look at opening up an issue with the Org repo.
