### ISSUE TITLE
openssl vs gnutls as tls-program

### ISSUE THREAD

**Issue by RafalBabinicz** [skeeto/elfeed#41]
In emacs we have `tls-program` variable which defaults to:

``` emacs-lisp
(setq tls-program '("gnutls-cli --insecure -p %p %h" "gnutls-cli --insecure -p %p %h --protocols ssl3" "openssl s_client -connect %h:%p -no_ssl2 -ign_eof"))
```

After changing it for example to:

``` emacs-lisp
(setq tls-program '("openssl s_client -connect %h:%p -no_ssl2 -ign_eof"))
```

and updating some feed with `elfeed-update-feed` I still can see error like this:
`gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.`

And here I'm not sure if I really changed to openssl or not?

How can I check if elfeed is using openssl, because I _feel_ that with latter setting (openssl as tls-program) I have **less** gnutls errors during update.

Additional info:
gnutls-cli 3.3.6
openssl 1.0.1.h-1

**Comment by skeeto** [comment]
Closing since this was addressed by switching to curl for the backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/).
