### ISSUE TITLE
(SOLVED) Question: How to have feed list not in init.el

### ISSUE THREAD

**Issue by danrobi11** [skeeto/elfeed#421]
I have over 300 feeds. I dont want 300+ feeds list in my init.el.
I've spend a few hrs searching. I've seen that its possible with elfeed.org. 
Possible to have feed list to load from elsewhere than my init.el without elfeed.org ?

**Comment by meliache** [comment]
You can load arbitrary lisp code from other files in your init file, so you can just put the `(setq elfeed-feeds ...)` in a separate `.el` file and load it from your init file. E.g. if you want to have it in `~/emacs.d/etc/elfeeds/feeds.el`, you can use:
``` elisp
(load (expand-file-name "etc/elfeed/feeds.el" user-emacs-directory))
```
(this directory scheme is adopted from [no-littering.el](https://github.com/emacscollective/no-littering). Or just put it anywhere with
``` elisp
(load (expand-file-name "~/path/to/feeds.el"))
```

**Comment by danrobi11** [comment]
@meliache Thank you much !!
