### ISSUE TITLE
How to mark entry as read after browse url with eww?

### ISSUE THREAD

**Issue by 404cn** [skeeto/elfeed#425]
I didn't find if there a hook about browse url .

**Comment by tsdh** [comment]
I just encountered that, too, and preparing a PR fixing that behavior.

**Comment by tsdh** [comment]
@404cn Should be fixed with PR #426.

**Comment by 404cn** [comment]
@tsdh  I add an advice and it worked.

`
  (advice-add 'elfeed-search-browse-url
              :before
              #'elfeed-search-untag-all-unread)
`

**Comment by tsdh** [comment]
@404cn Yes, that's a workaround.  But I'd still suggest to re-open this issue.  Users of emacs-internal browsers shouldn't need to write advices to get a working experience.
