### ISSUE TITLE
Multibyte characters broken in titles, fixed by running `toggle-enable-multibyte-characters` twice

### ISSUE THREAD

**Issue by meliache** [skeeto/elfeed#437]
I get numerical characters for multibyte characters in feed titles, see this screenshot:

![grafik](https://user-images.githubusercontent.com/5121824/129056233-245d316a-58bc-47a3-b6df-738ece91237e.png)

Somehow, calling `M-x toggle-enable-multibyte-characters` *twice* fixes the multibyte character display.

Any ideas to what might cause this or how to debug this? E.g. what functions to step through, what variables and environment variables to check?

## System and version information

I use the latest elfeed commit 243add9 with `(setq elfeed-use-curl t)`. Also as seen in the screenshot, I use `elfeed-goodies`, but disabling it doesn't fix the problem, so it's not the cause.

I use the master of the pure-gtk emacs fork with native-compile, runnin `M-X emacs-version` prints
```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-08-09
```

I'm on Archlinux and have some locale settings which are a mixture of english and german for different `LC_...` variables, but launching emacs with `LC_ALL=C` also didn't fix this issue.

**Comment by bhepple** [comment]
It looks like the solution above only applies to the titles of **new** items in the feed - it does not fix old titles. That's good enough for me.
