### ISSUE TITLE
not launching more than once after recompiling.

### ISSUE THREAD

**Issue by Napeer** [skeeto/elfeed#453]
I'm using doom-emacs and emacs-daemon. After recompiling(SPC-h-r-r) emacs, elfeed will launch once, and then if launched again via M-x elfeed,  gives this error
``
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-absolute-p(nil)
  (if (file-name-absolute-p (car rmh-elfeed-org-files)) nil (let* ((default-directory org-directory) (files (mapcar #'expand-file-name rmh-elfeed-org-files))) (let ((--dolist-tail-- (cl-remove-if #'file-exists-p files))) (while --dolist-tail-- (let ((file (car --dolist-tail--))) (message "elfeed-org: ignoring %S because it can't be read" file) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq rmh-elfeed-org-files (cl-remove-if-not #'file-exists-p files))))
  +rss-skip-missing-org-files-a()
  apply(+rss-skip-missing-org-files-a nil)
  elfeed()
  funcall-interactively(elfeed)
  call-interactively(elfeed record nil)
  command-execute(elfeed record)
  execute-extended-command(nil "elfeed" #("elfeed" 0 6 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "elfeed" #("elfeed" 0 6 (ws-butler-chg chg)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
``
It will also launch if I restart emacs-daemon

**Comment by Napeer** [comment]
The buffer was simply in another workspace within emacs. Strange behavior in my opinion, but more or less working as intended.

**Comment by Seanld** [comment]
I'm getting the same issue, but it's not listed anywhere in Ibuffer. I have to entirely restart Emacs to get Elfeed to open again.
