### ISSUE TITLE
Problem with Zotero feed

### ISSUE THREAD

**Issue by mardukbp** [skeeto/elfeed#46]
I set up my Zotero feed, which uses an https URL. Unfortunately, `url-retrieve` is not able to retrieve it. The error comes from gnutls. I tested it with gnutls-cli. However, `mm-url-insert` has no problem with it. I also tried giving elfeed the local URL `file:///path/to/feed.xml` to the feed but it complains with `void-variable url-http-end-of-headers`. I really need to get this working, elfeed is becoming an essential tool in my workflow.

**Comment by skeeto** [comment]
Closing since this should be fixed by the switch to the curl backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/)
