### ISSUE TITLE
Number of entries fetched after the first elfeed-update

### ISSUE THREAD

**Issue by grolongo** [skeeto/elfeed#460]
Hello,

Why does Elfeed only fetches a few entries when I use `elfeed-update` for the first time?

For example, starting from a blank state, I added `(setq elfeed-feeds '("http://www.masteringemacs.org/feed" blog emacs))`

After `elfeed-update`, I get only the last 3 most recent articles from this feed, while there are many others articles available: https://www.masteringemacs.org/all-articles

I don't know exactly how RSS works, so I can't tell if this is something because of the way RSS is configured on the website side (like only send 3 articles at a time) or something with Elfeed configuration/limitation.

Any clue?

**Comment by skeeto** [comment]
Your first guess was correct: The host is configured only to list three 
items in its feed (or perhaps has a short cutoff date). Elfeed is strictly 
a feed reader and doesn't go looking around the site for more articles 
itself. Feeds sometimes support a URL parameter for requesting a specific 
number of items. Though I don't see an obvious way to do that with this 
feed, and it's unlikely to support such a parameter.

**Comment by grolongo** [comment]
Thanks for the explanation.
As I understand it if I was trying to fetch more entries that would turn Elfeed into a scraper rather than a simple feed reader.

Thank you for Elfeed, have a great day!
