### ISSUE TITLE
Elfeed is frozen in latest Emacs 29 build

### ISSUE THREAD

**Issue by Crandel** [skeeto/elfeed#487]
After updating to latest Emacs v 29 from Arch Aur repo Elfeed is completely frozen and do not react on any keybinding. Same behavior with `emacs -Q`. Even with one feed in `elfeed-feeds`. 

`htop` is showing curl process as child process too

OS: Arch linux
Emacs: 29.0

**Comment by skeeto** [comment]
Hmm, I cannot reproduce on building either emacs-29.0.91 or the emacs-29 
branch (at bdb0bc2b4e4), including JIT, built on Debian 10. I wonder if 
inferior processes are somehow broken in the AUR build. Elfeed connects 
pipes to subprocesses, which isn't the default (945765a) and so could be 
missed in other testing. Here's a small, isolated test to evaluate in the 
scratch buffer:

(with-temp-buffer
  (let ((process-connection-type nil)
        (curl (start-process "test" (current-buffer) "curl" "--version")))
    (while (process-live-p curl)
      (accept-process-output curl))
    (buffer-string)))

If that locks up Emacs — and it normally should not — then you'll have a 
simpler starting point to find the source of the issue.

**Comment by Crandel** [comment]
Looks like fresh build had fixed this issue and elfeed is responsive again.
