### ISSUE TITLE
Lisp error: (void-function s-match)

### ISSUE THREAD

**Issue by sjLambda** [skeeto/elfeed#491]
Debugger entered--Lisp error: (void-function s-match)
  s-match("^\\[\\[\\(http.+?\\)\\]\\[\\(.+?\\)\\]\\]" "http://emacs.stackexchange.com/feeds")
  #f(compiled-function (headline) #<bytecode -0x1914c60a3964407a>)(("http://emacs.stackexchange.com/feeds" emacs stackexchange))
  mapcar(#f(compiled-function (headline) #<bytecode -0x1914c60a3964407a>) (("http://emacs.stackexchange.com/feeds" emacs stackexchange) 
/snip ...
all items from elfeed.org appear here, snipped for brevity
.../snip
  apply(rmh-elfeed-org-process-advice nil)
  elfeed()
  funcall-interactively(elfeed)
  call-interactively(elfeed nil nil)
  command-execute(elfeed)
================================
versions:
elfeed 3.4.1
emacs: latest truck complied from Savannah sources
M-x version:  GNU Emacs 30.0.50 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.61 Version 10.13.6

**Comment by skeeto** [comment]
This is a bug in ***@***.***, committed last week. See 
remyhonig/elfeed-org#83.
