### ISSUE TITLE
(elfeed-deref (elfeed-entry-tags entry)) doesn't work

### ISSUE THREAD

**Issue by danielkrajnik** [skeeto/elfeed#496]
I've been trying for the past three days to get elfeed to display desktop notifications. It was suggested that `'elfeed-new-entry-hook` can be used and it works, but parsing is a huge trial and error.

I added ` "https://lorem-rss.herokuapp.com/feed?unit=second&interval=10"` feed to be able to test it.

This works for example:

```lisp
(add-hook 'elfeed-new-entry-hook
          (lambda (entry)
            (alert (elfeed-deref (elfeed-entry-content entry))
                   :title (concat
                           (elfeed-deref (elfeed-entry-title entry)) " -_ "
                           (elfeed-deref (elfeed-entry-title entry))
                           )
                   :severity 'high
                   )))

```

But changing `elfeed-entry-title` to `elfeed-entry-tags` or `elfeed-entry-`feed` makes it fail (no notifications appear anymore).

Does anyone have any idea why?

**Comment by danielkrajnik** [comment]
[Solved it](https://www.reddit.com/r/emacs/comments/16yq0ww/elfeedderef_elfeedentrytags_entry_doesnt_work/):

```lisp
(defun elfeed-desktop-notifications (entry)
  "Parse and display new feeds as desktop notifications."
  (alert (elfeed-deref (elfeed-entry-content entry))
         :title (concat
                 (elfeed-feed-title (elfeed-deref (elfeed-entry-feed entry))) "\n"
                 (elfeed-deref (elfeed-entry-title entry))
                 )
         :severity 'high
         ))

(add-hook 'elfeed-new-entry-hook #'elfeed-desktop-notifications)
````

**Comment by danielkrajnik** [comment]
On a general note, I wish elisp had some typing system? I get that there are conventions, but as you mentioned developers may not always stick to them (elfeed as shown above did though) and if you are new it might have been easier?

On a tangential note, I wish desktop notifications had a "subtitle".

On a philosophical note, I haven't seen an emacs pacakage yet that had desktop notifications integrated out-of-the-box? I really wonder why? They are useful, no?

**Comment by sp1ff** [comment]
danielkrajnik ***@***.***> writes:

> On a general note, I wish elisp had some typing system? I get 
> that there are conventions, but as you
> mentioned developers may not always stick to them (elfeed as 
> shown above did though) and if you are new it
> might have been easier?

But it does? See here: 
<https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Lisp-Data-Types>

> On a tangential note, I wish desktop notifications had a 
> "subtitle".
>
> On a philosophical note, I haven't seen an emacs pacakage yet 
> that had desktop notifications integrated
> out-of-the-box? I really wonder why? They are useful, no?

Support for Freedesktop notifications is built-in

<https://www.gnu.org/software/emacs/manual/html_node/elisp/Desktop-Notifications.html>

and John Wiegly has a package (of course) that I believe is 
cross-platform:

<https://github.com/jwiegley/alert>


-- 
Michael ***@***.***>

**Comment by danielkrajnik** [comment]
> and John Wiegly has a package (of course) that I believe is
cross-platform:
<https://github.com/jwiegley/alert>

I am actually using this package in this example, but AFAIK it doesn't have a "subtitle" property (please see the image below):
![image](https://github.com/skeeto/elfeed/assets/15096799/6662ed87-1b95-4f70-90c4-2a786f846b95)
