### ISSUE TITLE
Please add a 3.4.2 tag

### ISSUE THREAD

**Issue by jiacai2050** [skeeto/elfeed#534]
So I can install this package with `use-package :vc`, thanks!

**Comment by skeeto** [comment]
Hmm, there's been a 3.4.2 tag for 5 months now:

https://github.com/skeeto/elfeed/tree/3.4.2

Though I notice I neglected to make a GitHub "Release" for it. I did that 
just now:

https://github.com/skeeto/elfeed/releases/tag/3.4.2

Is that what was missing for your use case?

**Comment by jiacai2050** [comment]
Thanks, it works well for me!

With Emacs 30, we can install elfeed like this:
```el
(use-package elfeed
  :vc (elfeed :url "https://github.com/skeeto/elfeed"
              :rev "3.4.2"))
```
