### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by trenkert** [skeeto/elfeed#55]
I love elfeed. In my books, it ranks before RSSOwl and QuiteRSS, which are two very fine feed readers.

I miss the option to create folders, though, not only tags. The folder pane could be displayed in a separate window or something like speedbar. Would it be possible to include this?

**Comment by clemera** [comment]
> It's not something I'll ever use myself and I feel would be extraneous.
But I think it could be done entirely as an extension

I would like to give this a try. Folders are nice when you have lots of feeds and you browse through the hierarchy to then only refresh the feeds for some subtopic you are currently interested in. Though maybe I'm just very used to this workflow, I have used thunderbird for quite some time. I'm not familiar with elfeeds code could you give me some rough pointers what you think would make the most sense on top of how elfeed manages feeds? Is it feasible to write such an extension at this point?

In case you have missed it there was a nice post about elfeed recently shared on [reddit](https://www.reddit.com/r/emacs/comments/g6oowz/elfeed_rules/).
