### ISSUE TITLE
Optional and more liberal handling of not well-formed XML (especially ‘&’).

### ISSUE THREAD

**Issue by RafalBabinicz** [skeeto/elfeed#59]
Is it possible to handle not well-formed XML on our side
or at least allow '&'?

If I have some troubles with

```
Elfeed update failed for http://swannodette.github.com/atom.xml: (error XML: (Not Well-Formed) Invalid entity reference)
```

then this is almost always ‘&’. 

Sometimes content providers do not react properly for notifications to fix not well-formed content.
Disabling feed is a little too harsh solution.
Escape hatch in form of — ok, I will allow ‘&’ — would be helpful in such situations.

http://bitemyapp.com/rss.xml

```
XML Parsing Error: not well-formed
Location: http://bitemyapp.com/rss.xml
Line Number 11, Column 56:    <title>Parsing and rendering templates in Clojure & Haskell</title>
-------------------------------------------------------^
```

http://swannodette.github.com/atom.xml

```
XML Parsing Error: not well-formed
Location: http://swannodette.github.io/atom.xml
Line Number 128, Column 26:   <title>Transit, JSON & ClojureScript</title>
-------------------------^
```

**Comment by skeeto** [comment]
Closing since this is almost 4 years old and outside of Elfeed's control.
