### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by Enrico68** [skeeto/elfeed#62]
Sorry for this _generic_ question. After playing a little with elfeed I could not figure out if there is a possibility to seach _inside_ the feed. As I am using for 2/3 feeds from journal, it would be really useful to search inside the abstract.

**Comment by pedrormjunior** [comment]
It would be a great feature for me. Did we have any advance in this direction since 2014?

**Comment by skeeto** [comment]
My original plan was to use SQLite as the Elfeed database backend, and I 
wrote EmacSQL to that end:

Introducing EmacSQL
https://nullprogram.com/blog/2014/02/06/

Then I could leverage the full text search feature, which EmacSQL 
explicitly enables. However, I wasn't satisfied enough with the result, 
and how complicated it was as a dependency, so I dropped those plans. 
Currently I have no plans to allow searching within entry content.

**Comment by e3bc54b2** [comment]
Hi,
I also stumbled across this after trying to look for a way to do full text search within elfeed feeds.

Is there any progress made on that, and if yes, how can I help test it?

**Comment by rtrppl** [comment]
This would really be a great feature for those of us who are monitoring rss-feeds for specific terms. In this regard, I tried playing around with your code but struggle a bit with the common lisp parts (and the complexity). Is there a simple way / function to get from the SHA-1 ID of a filename (listed in the index) to the correct ID of an entry? It would be trivial (and quick) to use ripgrep to filter all relevant entries.

**Comment by rtrppl** [comment]
Ok, I've put together a [small package](https://github.com/rtrppl/cuckoo-search) for content-based search. After some difficulties in the beginning it was rather easy. A warning: this works but is not very beautiful (and requires rg).
