### ISSUE TITLE
Author names with feeds

### ISSUE THREAD

**Issue by prtkm** [skeeto/elfeed#68]
Hi,

I was trying to use elfeed to fetch rss feeds from scientific journals, and was wondering if there is any way to display the author information along with the article title? 

I previously had tried gnus for this, which displayed the author names.

Prateek

**Comment by skeeto** [comment]
Unfortunately, the entry listing format isn't easily customizable right
now. The elfeed-search-print function is the key function for this, but
it has no hooks. I need to consider how to open it up to customization.

I was going to suggest using a new entry hook (elfeed-new-entry-hook) to
put the author's name in the title, but that information would be wiped
out on the next update to match the original title. There's probably
some terrible hack that would work using "around" advice and temporarily
rebinding elfeed-entry-title via noflet as entries are printed.

**Comment by prtkm** [comment]
Thanks for the reply! I guess I'll wait till its more customizable.

**Comment by algernon** [comment]
See #115, that makes the search buffer customisable, and will allow one to add the author information too.

**Comment by skeeto** [comment]
Fixed by #115.
