### ISSUE TITLE
[WISH] Ability to sort feeds by feed source, not only date

### ISSUE THREAD

**Issue by cig0** [skeeto/elfeed#71]
Hi,
I already read about the tagging system but I'm unsure if that would be the best way to accomplish this, could anybody point me in the right direction?

EDIT: the filtering function works very well, but I would still like to have the feeds ordered by source.

**Comment by skeeto** [comment]
Fixed in b62a2d0040f1a8ad0a23a48e3843d2ed5cbc2a8c.
