### ISSUE TITLE
[WISH] Ability to open feeds on a side-by-side panel

### ISSUE THREAD

**Issue by cig0** [skeeto/elfeed#72]
This would  make reading RSS much more enjoyable.

**Comment by jinnovation** [comment]
One possible implementation of this: redefine `elfeed-search-show-entry` to take a prefix argument, in the presence of which it shows the entry in an `other-window`.

**Comment by skeeto** [comment]
Added in f070b00f65cb9274bb84b0fe6f703e93b3d455fe.
