### ISSUE TITLE
Toggle Tags 

### ISSUE THREAD

**Issue by angelic-sedition** [skeeto/elfeed#75]
I currently have a key bound to `'(lambda () (interactive) (elfeed-search-tag-all '*))` for "starring" an entry. I think a `elfeed-search-tag-toggle` would be nice that would either add the tag if it didn't exist or removed it if it did.

**Comment by skeeto** [comment]
Good idea, thanks! I decided to call it elfeed-search-toggle-all to be
more consistent.

**Comment by angelic-sedition** [comment]
Great! Thanks for the quick response.
