### ISSUE TITLE
[FEATURE] Ability to rename feeds

### ISSUE THREAD

**Issue by jinnovation** [skeeto/elfeed#78]
Sometimes feed names carry some cruft that users might want to hide away or, for whatever reason, users might simply want to rename feeds to display as something else.

So I propose adding on to feed definitions with a `name` attribute, for example:

``` elisp
(setq elfeed-feeds
  '(("https://news.ycombinator.com/rss" software news
       :name "My Own Name For Hacker News")))
```

**Comment by skeeto** [comment]
I like this idea. I need to think about how exactly I'd want it to work. Elfeed already supports arbitrary metadata, originally added in case anyone needed it for extensions, through the setf-able `elfeed-meta` function. It all persists in the database automatically. Each entry and feed object has a plist attached. Some keys could be treated as special by Elfeed, like `:title` metadata that overrides the feed or entry's actual title when being displayed.

~~~el
(setf my-feed (elfeed-db-get-feed "http://example.com/feed/"))
(setf (elfeed-meta my-feed :title) "My Custom Title")
(elfeed-meta my-feed :title)
;; => "My Custom Title"
~~~

Currently there's no configuration mechanism for this, like in your example. Individual entries wouldn't make sense to configure in an init file, but feeds should be configurable at a high level.

**Comment by skeeto** [comment]
Forgot to reference this issue from the commit, but bd2d99e makes Elfeed use the `:title` metadata for both entries and feeds when available. The only thing missing is a nice configuration interface. Right now you can achieve it via a `setf` call in your config.

**Comment by caadar** [comment]
My current setup. Just for info.

```lisp

(defvar *feeds* '(("http://nullprogram.com/feed/" :tags (comp emacs) :title "Elfeed")))

(defvar *urls-titles* nil
  "URL-title list for feeds titles fixing.")

(defun elfeed/feeds-prepair (feeds)
  "Populate main `elfeed-feeds' list and aux `*urls-titles*' one."
  (setq elfeed-feeds)
  (mapc (lambda (feed)
		  (if (listp feed)
			  (let* ((url (first feed))
					 (meta (rest feed))
					 (tags (plist-get meta ':tags))
					 (title (plist-get meta ':title)))
				(cond ((null tags) (push url elfeed-feeds))
					  ((atom tags) (push (list url tags) elfeed-feeds))
					  (t (push (push url tags) elfeed-feeds)))
				(when title
				  (push (list url title) *urls-titles*)))
			(push feed elfeed-feeds)))
		feeds))

(defun elfeed/feeds-titles-fix (old-fun &rest args)
  "Advice titles fixing."
  (mapc (lambda (lst)
		  (let* ((url (first lst))
				 (title (second lst))
				 (feed (elfeed-db-get-feed url)))
			(setf (elfeed-feed-title feed) title)))
		*urls-titles*)
  (apply old-fun args))

(advice-add #'elfeed-search-update :around #'elfeed/feeds-titles-fix)

**Comment by vxcamiloxv** [comment]
+10

It would be a very good functionality

**Comment by Distopico** [comment]
+10 
It would be a very good functionality

**Comment by skeeto** [comment]
Closing since this was added in bd2d99e.
