### ISSUE TITLE
On feed updates: elfeed-handle-http-error: Wrong number of arguments: (3 . 3), 4 

### ISSUE THREAD

**Issue by mrvdb** [skeeto/elfeed#81]
On every update i get the message in the subject. Here's a slightly longer streak from the *messages* buffer:

```
Elfeed update: maart 29 2015 19:48:41 CEST
error in process filter: elfeed-handle-http-error: Wrong number of arguments: (3 . 3), 4
error in process filter: Wrong number of arguments: (3 . 3), 4
error in process filter: elfeed-handle-http-error: Wrong number of arguments: (3 . 3), 4
error in process filter: Wrong number of arguments: (3 . 3), 4
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated. [2 times]
HTTP error: (file-error Writing to process connection timed out oremacs.com<1>)
error in process sentinel: elfeed-handle-http-error: Wrong number of arguments: (3 . 3), 4
error in process sentinel: Wrong number of arguments: (3 . 3), 4
Auto-saving...done
Saving file /home/mrb/.emacs.d/feeds.org...
Wrote /home/mrb/.emacs.d/feeds.org
```

Ubuntu 14.10 / no desktop env (awesome wm) / emacs 24.5 rc1

**Comment by skeeto** [comment]
What's the value of your elfeed-http-error-hooks? It should be a list of
functions that accept two arguments (which includes an empty list).

Another possibility: have you updated Elfeed within the current session?
The semantics of elfeed-meta recently changed slightly, with some new
macro definitions, so you may have had some stale macros still kicking
around. If it persists across Emacs sessions -- perhaps the old macro
definitions were baked in by the compiler during the update -- try
reinstalling Elfeed (kill emacs; `rm -rf ~/.emacs.d/elpa/elfeed-*`;
restart emacs).

**Comment by mrvdb** [comment]
Reinstalled elfeed (I'm using an el-get recipe pointing to github), haven't seen the message since, so I guess your last suggestion was indeed the case. Thanks!

FYI:  my  elfeed-http-error-hooks is nil

**Comment by skeeto** [comment]
You're certainly not the only one with this problem. I'm pretty sure
there's a bug in the way the new (Emacs 24.3) generalized variables
system (gv) and package.el interact. The package's gv-* definitions
don't get redefined properly, like macros and functions normally do,
when a package is updated after having been loaded, so the new version
of a package uses the old macro definitions. It doesn't manifest here,
but there's also some breakage between gv and the cl-lib rename, so gv's
introduction, while welcome, has been kind of messy.
