### ISSUE TITLE
[FEATURE] `elfeed-search-browse-url` ability to open externally

### ISSUE THREAD

**Issue by jinnovation** [skeeto/elfeed#83]
Many times, `browse-url` is set to use text-based browser, such as `eww`, within Emacs, but there are many feeds that do not display well within Emacs. In such cases, user would then be required to call another function from within said browser to display the page in external browser. This is an extra step that can be easily circumvented by having an `elfeed-search-browse-url-external` function, possibly bound to `B`, that opens in external browser directly.

Another solution that I can think of is to redefine elfeed-search-browse-url to accept a prefix arg, in the presence of which case it'd open the URL externally.

**Comment by jinnovation** [comment]
Another solution that I can think of is to redefine `elfeed-search-browse-url` to accept a prefix arg, in which case it'd open the URL externally.

**Comment by skeeto** [comment]
Addressed by #84.
