### ISSUE TITLE
[Feature] Allow setting the face for unread items directly, instead of using the default bold.

### ISSUE THREAD

**Issue by atheriel** [skeeto/elfeed#86]
At the moment, the face for titles in the search mode can be modified with `elfeed-search-title-face`, but the `elfeed-search-print` function is hard-coded to bold unread items. This is a bit annoying for fonts that have ugly bold faces, or for bitmap/pixel fonts that have none at all. Is it possible to add an optional `elfeed-search-title-unread-face` for customization of unread items directly?

**Comment by skeeto** [comment]
Good idea! Fixed. The new face is elfeed-search-unread-title-face.

**Comment by atheriel** [comment]
Amazing! Thank you!
