### ISSUE TITLE
elfeed error updating

### ISSUE THREAD

**Issue by jvillasante** [skeeto/elfeed#88]
After installing emacs 24.5 elfeed stops working. This is the error I get when I try to update my feeds:
Elfeed fetch failed for http://***************: (:error (error url-queue-timeout "Queue timeout exceeded"))

**Comment by skeeto** [comment]
I recently switched queuing to Emacs' url-queue package. Unfortunately
it has a really low default timeout, so try increasing it to, say, 30
seconds. That should solve your problem.

    (setf url-queue-timeout 30)

I initially also had the same problem with the default value. I'll add a
note to the README about it. It would probably be worth getting the
default increased in Emacs itself upstream.

**Comment by kototama** [comment]
I have the same error, even after setting.
 
    (setf url-queue-timeout 30)

I get some "Queue timeout exceeded" errors on feeds that exist otherwise.

**Comment by skeeto** [comment]
@kototama What OS and Emacs version are you running? Does it completely
lock up on you while fetching feeds?

If it's still giving you "timeout exceeded" that means Emacs starts a
timer for 30 seconds, fires off the DNS lookup, then the TCP connection,
and Emacs doesn't receive a full HTTP response from the server before
the timer completes. A few reasons this might happen:

* Another feed responds with a massive chunk of XML and it takes a long
time to parse. To solve this Elfeed would need to parse XML in an async
process and changing the timeout wouldn't be of much help.

* DNS lookups are synchronous in Emacs 24, so if DNS was slow to respond
it will cause feeds fetched in parallel to timeout. This will be fixed
in the upcoming Emacs 25. Increasing the timeout beyond the DNS timeout
would partially fix this, but you'll still have the annoying problem of
Emacs locking up for a minute at a time, and it may still disrupt other
feeds.

* On Windows, TCP connections are established synchronously, so a single
slow feed host will cause feeds fetched in parallel to timeout. It
manifests very similarly to the DNS issue above, but is much more common
(and part of what makes Elfeed essentially unusable on Windows).

**Comment by kototama** [comment]
I'm using Emacs 24.5 and Manjaro Linux. I cannot move the cursor or do anything when fetching the feeds. All the feeds seem rather normal to me (checked with firefox) and not specially big.

Maybe you want to test with my list of feeds? I could send it to you by email if you want and have the time to check.

**Comment by litanlitudan** [comment]
@kototama I got the same problem as you on mac.

**Comment by skeeto** [comment]
Closing since this should be fixed by the switch to the curl backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/)
