### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by Eilie** [skeeto/elfeed#94]
How do I add youtube channel to elfeed to get video updates?

**Comment by Eilie** [comment]
Found it in page source: grep for channel-external-id and use it with https://www.youtube.com/feeds/videos.xml?channel_id=.

**Comment by skeeto** [comment]
Here's a whole bunch more discussion about it:

https://www.reddit.com/r/youtube/comments/339idg/youtube_just_dropped_its_support_for_rssatom_feeds/

Unfortunately it's not as powerful and flexible as the old v2 API, but it's better than nothing, like when Twitter completely dropped RSS support 2 years ago.
