### ISSUE TITLE
End of file during parsing

### ISSUE THREAD

**Issue by smythp** [skeeto/elfeed#95]
On installing Elfeed (either manually or through MELPA) and running M-x elfeed, I get the message "End of file during parsing" in the minibuffer. _Messages_ says it's a problem with elfeed-db-load, but not seeing any unbalanced parens or anything in that function. Any ideas what could be causing this?

**Comment by smythp** [comment]
The index file was corrupted. Deleted it and now Elfeed is working.

**Comment by danlamanna** [comment]
I also encountered this and noticed my index file was size 0. I'm not sure how/why this happened but I'll keep an eye out in the future.

**Comment by skeeto** [comment]
If your write-region-inhibit-fsync is non-nil, then this is a possible
outcome from a system crash or power failure. Since Emacs doesn't use
"fcntl(F_FULLFSYNC)" I believe it's effectively always non-nil for
macOS.

**Comment by skeeto** [comment]
Closing since this is an old issue and a lot has changed.

**Comment by FrostyX** [comment]
This issue happened to me years later (Jan 2023) and removing `~/.elfeed/index` didn't help. However, thank you for the tip @smythp because removing `~/.emacs.d/var/elfeed/db/index` worked.

**Comment by smythp** [comment]
Glad my issue and comment from...eight years ago, yikes...was a help. Have an Emacs-filled 2023.
