### ISSUE TITLE
[FEATURE] User-customizable date formats for `elfeed-search-format-date` etc

### ISSUE THREAD

**Issue by jinnovation** [skeeto/elfeed#96]
`elfeed-search-format-date` is currently defined as follows:

``` emacs-lisp
(defun elfeed-search-format-date (date)
  "Format a date for printing in elfeed-search-mode."
  (let ((string (format-time-string "%Y-%m-%d" (seconds-to-time date))))
    (format "%-10.10s" string)))
```

What are your thoughts on making the string `"%Y-%m-%d"` a customizable variable, possibly named `elfeed-date-format`, that defaults in value to `"%Y-%m-%d"` but opens up the option to the user to customize it? With additional checks for valid formatting, of course.

Similar patches could be made for formatting the output of `elfeed-search-insert-header` etc.

**Comment by skeeto** [comment]
Sorry, I forgot to address this issue for a few days.

I'm not opposed to this being a new customization variable. There's just
slightly more to it. The result of the output of format should have a
uniform width. Currently that's 10, as enforced by the second format
string. So it should be both a date format string and a width. I don't
care about validating the string itself (if a user breaks it with a bad
format string, they get to keep both pieces).

**Comment by skeeto** [comment]
Just added `elfeed-search-date-format`.
